// <auto-generated />
using System;
using LearnConnect.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnConnect.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260427061649_InitialPostgreSQL")]
    partial class InitialPostgreSQL
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnConnect.API.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("LessonPackageId")
                        .HasColumnType("integer");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonPackageId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonNotebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonNotebooks");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RemainingLessons")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonPackages");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LearnConnect.API.Models.ParentMeetingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ParentMeetingRequests");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLessonDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int?>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStreak = 0,
                            ExperiencePoints = 0,
                            Level = 1,
                            Location = "New York, USA",
                            PhoneNumber = "+1234567890",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.StudentBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentBadges");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Science",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Science",
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Science",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Science",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Languages",
                            Name = "English"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Languages",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Languages",
                            Name = "French"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Technology",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Technology",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Humanities",
                            Name = "History"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Humanities",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Arts",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Arts",
                            Name = "Piano"
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Languages")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MemberSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ResponseTime")
                        .HasColumnType("text");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.7999999999999998,
                            Bio = "Experienced mathematics teacher with 10+ years of teaching experience. Specialized in calculus and algebra.",
                            Education = "PhD in Mathematics, MIT",
                            HourlyRate = 45.00m,
                            Languages = "English,Spanish",
                            Location = "Boston, USA",
                            MemberSince = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567891",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 250,
                            UserId = 3,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 4.9000000000000004,
                            Bio = "Computer Science expert specializing in Python, Java, and web development. Former software engineer at Google.",
                            Education = "MS in Computer Science, Stanford University",
                            HourlyRate = 60.00m,
                            Languages = "English,Mandarin",
                            Location = "San Francisco, USA",
                            MemberSince = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567892",
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 180,
                            UserId = 4,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 4.7000000000000002,
                            Bio = "Native English speaker with TEFL certification. Helping students improve their English communication skills.",
                            Education = "BA in English Literature, Oxford University",
                            HourlyRate = 35.00m,
                            Languages = "English,French",
                            Location = "London, UK",
                            MemberSince = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567893",
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 320,
                            UserId = 5,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2019, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 4.9000000000000004,
                            Bio = "Physics enthusiast with a passion for making complex concepts simple. Specialized in mechanics and electromagnetism.",
                            Education = "PhD in Physics, Caltech",
                            HourlyRate = 50.00m,
                            Languages = "English,Spanish,Portuguese",
                            Location = "Chicago, USA",
                            MemberSince = new DateTime(2018, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567894",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 290,
                            UserId = 6,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2018, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 5.0,
                            Bio = "Professional pianist and music teacher. Teaching piano, music theory, and composition for all levels.",
                            Education = "Master of Music, Juilliard School",
                            HourlyRate = 40.00m,
                            Languages = "English,German,Italian",
                            Location = "Vienna, Austria",
                            MemberSince = new DateTime(2017, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567895",
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 450,
                            UserId = 7,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2017, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 4.5999999999999996,
                            Bio = "Chemistry teacher with expertise in organic and inorganic chemistry. Making chemistry fun and understandable!",
                            Education = "PhD in Chemistry, University of Toronto",
                            HourlyRate = 42.00m,
                            Languages = "English,French",
                            Location = "Toronto, Canada",
                            MemberSince = new DateTime(2020, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567896",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 210,
                            UserId = 8,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 9
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 4.7999999999999998,
                            Bio = "Native Spanish speaker offering conversational Spanish lessons. Learn Spanish the natural way!",
                            Education = "BA in Spanish Linguistics, Universidad Complutense",
                            HourlyRate = 30.00m,
                            Languages = "Spanish,English,Catalan",
                            Location = "Madrid, Spain",
                            MemberSince = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567897",
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 380,
                            UserId = 9,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 4.7000000000000002,
                            Bio = "History professor specializing in World War II and American history. Bringing history to life through engaging storytelling.",
                            Education = "PhD in History, Harvard University",
                            HourlyRate = 38.00m,
                            Languages = "English",
                            Location = "Washington DC, USA",
                            MemberSince = new DateTime(2016, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567898",
                            ResponseTime = "Within 5 hours",
                            TotalLessons = 340,
                            UserId = 10,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2016, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 4.9000000000000004,
                            Bio = "Biology teacher with a focus on molecular biology and genetics. PhD researcher turned educator.",
                            Education = "PhD in Molecular Biology, Cambridge University",
                            HourlyRate = 48.00m,
                            Languages = "English,French",
                            Location = "Cambridge, UK",
                            MemberSince = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567899",
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 195,
                            UserId = 11,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 4.7999999999999998,
                            Bio = "French language expert offering lessons from beginner to advanced. Certified DELF/DALF examiner.",
                            Education = "MA in French Literature, Sorbonne University",
                            HourlyRate = 36.00m,
                            Languages = "French,English,Spanish",
                            Location = "Paris, France",
                            MemberSince = new DateTime(2019, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567800",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 420,
                            UserId = 12,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 11
                        },
                        new
                        {
                            Id = 20,
                            AverageRating = 4.5,
                            Bio = "Math enthusiast helping students love numbers.",
                            Education = "BS Math",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 50,
                            UserId = 20,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 21,
                            AverageRating = 5.0,
                            Bio = "Advanced mathematics for serious students.",
                            Education = "PhD Math",
                            HourlyRate = 75.00m,
                            Languages = "English",
                            Location = "New York",
                            MemberSince = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 500,
                            UserId = 21,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 22,
                            AverageRating = 4.5999999999999996,
                            Bio = "Physics made simple and fun.",
                            Education = "BS Physics",
                            HourlyRate = 28.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 80,
                            UserId = 22,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 23,
                            AverageRating = 4.9000000000000004,
                            Bio = "Expert physics tutoring for university level.",
                            Education = "PhD Physics",
                            HourlyRate = 70.00m,
                            Languages = "English,French",
                            Location = "Paris",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 6 hours",
                            TotalLessons = 300,
                            UserId = 23,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 24,
                            AverageRating = 4.7000000000000002,
                            Bio = "High school chemistry support.",
                            Education = "BS Chemistry",
                            HourlyRate = 30.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 120,
                            UserId = 24,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 25,
                            AverageRating = 5.0,
                            Bio = "Advanced organic chemistry and lab prep.",
                            Education = "PhD Chemistry",
                            HourlyRate = 80.00m,
                            Languages = "English,German",
                            Location = "Berlin",
                            MemberSince = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 24 hours",
                            TotalLessons = 600,
                            UserId = 25,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 25
                        },
                        new
                        {
                            Id = 26,
                            AverageRating = 4.4000000000000004,
                            Bio = "Biology basics for everyone.",
                            Education = "BS Biology",
                            HourlyRate = 22.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 30,
                            UserId = 26,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 27,
                            AverageRating = 4.7999999999999998,
                            Bio = "Genetics and evolutionary biology expert.",
                            Education = "MS Biology",
                            HourlyRate = 45.00m,
                            Languages = "English,German",
                            Location = "Vienna",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 200,
                            UserId = 27,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 28,
                            AverageRating = 4.2999999999999998,
                            Bio = "English conversation and grammar.",
                            Education = "BA English",
                            HourlyRate = 20.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 40,
                            UserId = 28,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 29,
                            AverageRating = 4.9000000000000004,
                            Bio = "Literature analysis and creative writing.",
                            Education = "MFA Writing",
                            HourlyRate = 65.00m,
                            Languages = "English",
                            Location = "London",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 5 hours",
                            TotalLessons = 350,
                            UserId = 29,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 30,
                            AverageRating = 4.7000000000000002,
                            Bio = "Spanish for travel and business.",
                            Education = "BA Spanish",
                            HourlyRate = 40.00m,
                            Languages = "Spanish,English",
                            Location = "Barcelona",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 150,
                            UserId = 30,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 31,
                            AverageRating = 4.9000000000000004,
                            Bio = "Native Spanish speaker, advanced levels.",
                            Education = "MA Linguistics",
                            HourlyRate = 60.00m,
                            Languages = "Spanish,English",
                            Location = "Madrid",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 280,
                            UserId = 31,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 32,
                            AverageRating = 4.5,
                            Bio = "Learn French basics quickly.",
                            Education = "BA French",
                            HourlyRate = 25.00m,
                            Languages = "French,English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 60,
                            UserId = 32,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 33,
                            AverageRating = 5.0,
                            Bio = "Master French cuisine and language.",
                            Education = "Culinary Arts",
                            HourlyRate = 70.00m,
                            Languages = "French,English",
                            Location = "Paris",
                            MemberSince = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 8 hours",
                            TotalLessons = 400,
                            UserId = 33,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 34,
                            AverageRating = 4.5999999999999996,
                            Bio = "Intro to coding and cybersecurity.",
                            Education = "Self-taught",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 90,
                            UserId = 34,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 35,
                            AverageRating = 4.7999999999999998,
                            Bio = "DevOps, Linux, and System Admin.",
                            Education = "MS CS",
                            HourlyRate = 55.00m,
                            Languages = "English,Finnish",
                            Location = "Helsinki",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 220,
                            UserId = 35,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 36,
                            AverageRating = 5.0,
                            Bio = "Artificial Intelligence and Machine Learning.",
                            Education = "PhD CS",
                            HourlyRate = 90.00m,
                            Languages = "English",
                            Location = "San Francisco",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 180,
                            UserId = 36,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 37,
                            AverageRating = 4.4000000000000004,
                            Bio = "History through the ages.",
                            Education = "BA History",
                            HourlyRate = 20.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 45,
                            UserId = 37,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 38,
                            AverageRating = 4.7999999999999998,
                            Bio = "Archaeology and ancient civilizations.",
                            Education = "PhD Archaeology",
                            HourlyRate = 40.00m,
                            Languages = "English",
                            Location = "Cairo",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 6 hours",
                            TotalLessons = 300,
                            UserId = 38,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 39,
                            AverageRating = 4.7000000000000002,
                            Bio = "Reading comprehension and book clubs.",
                            Education = "BA Lit",
                            HourlyRate = 22.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 100,
                            UserId = 39,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 40,
                            AverageRating = 4.9000000000000004,
                            Bio = "Creative writing masterclass.",
                            Education = "BA Classics",
                            HourlyRate = 65.00m,
                            Languages = "English",
                            Location = "Edinburgh",
                            MemberSince = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 24 hours",
                            TotalLessons = 500,
                            UserId = 40,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 41,
                            AverageRating = 4.7999999999999998,
                            Bio = "Guitar and pop music basics.",
                            Education = "Self-taught",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "London",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 150,
                            UserId = 41,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 42,
                            AverageRating = 5.0,
                            Bio = "Classical piano and composition.",
                            Education = "Conservatory",
                            HourlyRate = 85.00m,
                            Languages = "German,English",
                            Location = "Vienna",
                            MemberSince = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 800,
                            UserId = 42,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2018, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 30
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            SubjectId = 8,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            SubjectId = 9,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            SubjectId = 5,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 5,
                            SubjectId = 11,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 6,
                            SubjectId = 2,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 7,
                            SubjectId = 12,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 8,
                            SubjectId = 13,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 9,
                            SubjectId = 3,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 10,
                            SubjectId = 6,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 11,
                            SubjectId = 10,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 12,
                            SubjectId = 4,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 13,
                            SubjectId = 7,
                            TeacherId = 10
                        },
                        new
                        {
                            Id = 14,
                            SubjectId = 11,
                            TeacherId = 10
                        },
                        new
                        {
                            Id = 20,
                            SubjectId = 1,
                            TeacherId = 20
                        },
                        new
                        {
                            Id = 21,
                            SubjectId = 1,
                            TeacherId = 21
                        },
                        new
                        {
                            Id = 22,
                            SubjectId = 2,
                            TeacherId = 22
                        },
                        new
                        {
                            Id = 23,
                            SubjectId = 2,
                            TeacherId = 23
                        },
                        new
                        {
                            Id = 24,
                            SubjectId = 3,
                            TeacherId = 24
                        },
                        new
                        {
                            Id = 25,
                            SubjectId = 3,
                            TeacherId = 25
                        },
                        new
                        {
                            Id = 26,
                            SubjectId = 4,
                            TeacherId = 26
                        },
                        new
                        {
                            Id = 27,
                            SubjectId = 4,
                            TeacherId = 27
                        },
                        new
                        {
                            Id = 28,
                            SubjectId = 5,
                            TeacherId = 28
                        },
                        new
                        {
                            Id = 29,
                            SubjectId = 5,
                            TeacherId = 29
                        },
                        new
                        {
                            Id = 30,
                            SubjectId = 6,
                            TeacherId = 30
                        },
                        new
                        {
                            Id = 31,
                            SubjectId = 6,
                            TeacherId = 31
                        },
                        new
                        {
                            Id = 32,
                            SubjectId = 7,
                            TeacherId = 32
                        },
                        new
                        {
                            Id = 33,
                            SubjectId = 7,
                            TeacherId = 33
                        },
                        new
                        {
                            Id = 34,
                            SubjectId = 8,
                            TeacherId = 34
                        },
                        new
                        {
                            Id = 35,
                            SubjectId = 9,
                            TeacherId = 34
                        },
                        new
                        {
                            Id = 36,
                            SubjectId = 8,
                            TeacherId = 35
                        },
                        new
                        {
                            Id = 37,
                            SubjectId = 9,
                            TeacherId = 35
                        },
                        new
                        {
                            Id = 38,
                            SubjectId = 8,
                            TeacherId = 36
                        },
                        new
                        {
                            Id = 39,
                            SubjectId = 9,
                            TeacherId = 36
                        },
                        new
                        {
                            Id = 40,
                            SubjectId = 10,
                            TeacherId = 37
                        },
                        new
                        {
                            Id = 41,
                            SubjectId = 10,
                            TeacherId = 38
                        },
                        new
                        {
                            Id = 42,
                            SubjectId = 11,
                            TeacherId = 39
                        },
                        new
                        {
                            Id = 43,
                            SubjectId = 11,
                            TeacherId = 40
                        },
                        new
                        {
                            Id = 44,
                            SubjectId = 12,
                            TeacherId = 41
                        },
                        new
                        {
                            Id = 45,
                            SubjectId = 13,
                            TeacherId = 41
                        },
                        new
                        {
                            Id = 46,
                            SubjectId = 12,
                            TeacherId = 42
                        },
                        new
                        {
                            Id = 47,
                            SubjectId = 13,
                            TeacherId = 42
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 40, 771, DateTimeKind.Utc).AddTicks(7933),
                            Email = "admin@learnconnect.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$P3KOsbHO9lX60zr6M.h5fuWXsDNcRZo.qDT7WHn3vejT88KOCQT46",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 40, 954, DateTimeKind.Utc).AddTicks(6697),
                            Email = "student@test.com",
                            FirstName = "Test",
                            IsActive = true,
                            LastName = "Student",
                            PasswordHash = "$2a$11$lHFVw/F6m8Rg9NbMB2SUZ.LHafb3LxKGCwtlimUrLvMu30XQU3vC.",
                            Role = 0
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 41, 170, DateTimeKind.Utc).AddTicks(4545),
                            Email = "parent@test.com",
                            FirstName = "Test",
                            IsActive = true,
                            LastName = "Parent",
                            PasswordHash = "$2a$11$QAYOCT5uSL.hgCrY.0Z7eOW1qODP3Xk7XNDyO3biyOVdL8xFAs97K",
                            Role = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 41, 344, DateTimeKind.Utc).AddTicks(9745),
                            Email = "sarah.johnson@learnconnect.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$cUDy0bdlJKrKI.aVFjY6S.Nxk9rzTN0Tx2brr2mRoFQ4zWQwHgXD6",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 41, 605, DateTimeKind.Utc).AddTicks(1027),
                            Email = "michael.chen@learnconnect.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Chen",
                            PasswordHash = "$2a$11$.eHToypa.WvMFousaB815Ot4dz5NrMJM9/f4.ymhIPLWpogCspfK6",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 41, 824, DateTimeKind.Utc).AddTicks(8084),
                            Email = "emma.davis@learnconnect.com",
                            FirstName = "Emma",
                            IsActive = true,
                            LastName = "Davis",
                            PasswordHash = "$2a$11$QlCqzeagga8K.Nxb.b/CFe49zlCg0426tjSBhKauTVmKmG0rSB1WO",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 42, 69, DateTimeKind.Utc).AddTicks(6998),
                            Email = "david.martinez@learnconnect.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Martinez",
                            PasswordHash = "$2a$11$5Cis8K4i8fZAOBsUilfwKuX4zQT6m9PiwoWsavzdenAr1Yo6kWdIO",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 42, 329, DateTimeKind.Utc).AddTicks(5734),
                            Email = "lisa.anderson@learnconnect.com",
                            FirstName = "Lisa",
                            IsActive = true,
                            LastName = "Anderson",
                            PasswordHash = "$2a$11$f5Z6jjqGXYnS3GHDukv/COFYZwJFg1M/WmoXSIfzBu.QUKJidGKWO",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 42, 568, DateTimeKind.Utc).AddTicks(4300),
                            Email = "james.wilson@learnconnect.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Wilson",
                            PasswordHash = "$2a$11$5H6/D.vNymtFa3AnvTm5AeFBj9rbLFjMB6lD2esJftYPkiTTH5EA2",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 42, 798, DateTimeKind.Utc).AddTicks(7253),
                            Email = "sophia.garcia@learnconnect.com",
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Garcia",
                            PasswordHash = "$2a$11$iZP.OsCW/MKWrPAflcHxBe8tNynmBI5zIVsLHKHL91A3dI1SVIvNu",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 42, 993, DateTimeKind.Utc).AddTicks(3880),
                            Email = "robert.brown@learnconnect.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Brown",
                            PasswordHash = "$2a$11$pkxg4aCD6uZ4bnj2HHOPfe8rto.SR7lDTeydCfQzQktd5omindbTa",
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 43, 248, DateTimeKind.Utc).AddTicks(7677),
                            Email = "olivia.taylor@learnconnect.com",
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Taylor",
                            PasswordHash = "$2a$11$WlaTI8yrV5sY6gb9apPm2uTvkCCVxk4UHBbWZkljKN8WxueylV3Ha",
                            Role = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 43, 429, DateTimeKind.Utc).AddTicks(3367),
                            Email = "daniel.moore@learnconnect.com",
                            FirstName = "Daniel",
                            IsActive = true,
                            LastName = "Moore",
                            PasswordHash = "$2a$11$47VnIX2gEFEv7bHxhLQ2I.bWTPevA0ihnXQoYCWmbmZHxr22yqkEa",
                            Role = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 43, 617, DateTimeKind.Utc).AddTicks(3534),
                            Email = "alice.walker@learnconnect.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Walker",
                            PasswordHash = "$2a$11$srAeptjE3Wy3vUsmbgcyb.f49yJviZKGnXq7lpILWW/86m8LAjM2e",
                            Role = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 43, 790, DateTimeKind.Utc).AddTicks(7335),
                            Email = "robert.vance@learnconnect.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Vance",
                            PasswordHash = "$2a$11$oUkrRtJnt.Z2sXSLYSP4A.1GkbpJbNzkXCLIYq.ZtkrJ1JiWoq4iC",
                            Role = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 43, 966, DateTimeKind.Utc).AddTicks(962),
                            Email = "john.doe@learnconnect.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$BEWa2bFpLPEV80tZrufj2uJknK51kLRaXNaj.qB/DB8MZm8l8GjGW",
                            Role = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 44, 157, DateTimeKind.Utc).AddTicks(2950),
                            Email = "marie.curie@learnconnect.com",
                            FirstName = "Marie",
                            IsActive = true,
                            LastName = "Curie",
                            PasswordHash = "$2a$11$OlQt7h3sZ4sXyRJ200SdkehqlioiMMOAtt.RdJ7CMJ9KiIjEnnnru",
                            Role = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 44, 338, DateTimeKind.Utc).AddTicks(3703),
                            Email = "walter.white@learnconnect.com",
                            FirstName = "Walter",
                            IsActive = true,
                            LastName = "White",
                            PasswordHash = "$2a$11$YL9tHizEqf1XK79BeTRM1e85kk7zvjGAeFh5jU/2HANHfKsry.xfC",
                            Role = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 44, 518, DateTimeKind.Utc).AddTicks(338),
                            Email = "heisenberg@learnconnect.com",
                            FirstName = "Werner",
                            IsActive = true,
                            LastName = "Heisenberg",
                            PasswordHash = "$2a$11$3OXGEDCiAx8rZiXi/zbGLelF0ERu8O0uFismYTewyufBaLlKnoAqa",
                            Role = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 44, 706, DateTimeKind.Utc).AddTicks(272),
                            Email = "jane.goodall@learnconnect.com",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Goodall",
                            PasswordHash = "$2a$11$9tjo2F/CjgBfCPlErprAc.U9pdIa2/sjkwWr9nSxZFfO7q48assmG",
                            Role = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 44, 894, DateTimeKind.Utc).AddTicks(5927),
                            Email = "gregor.mendel@learnconnect.com",
                            FirstName = "Gregor",
                            IsActive = true,
                            LastName = "Mendel",
                            PasswordHash = "$2a$11$ZE4inxZvjv8KkiXUUq2OSeo9XIwv0a.v4Wn7M0PJ2mRqCxvTbzhla",
                            Role = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 45, 246, DateTimeKind.Utc).AddTicks(9917),
                            Email = "new.grad@learnconnect.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Dickinson",
                            PasswordHash = "$2a$11$4SqVmVxPppO6e89QjdAUTuVsBRdBFcf99KAhzCTAmOxcYNx99Dbne",
                            Role = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 45, 456, DateTimeKind.Utc).AddTicks(3885),
                            Email = "shakespeare@learnconnect.com",
                            FirstName = "William",
                            IsActive = true,
                            LastName = "Shakespeare",
                            PasswordHash = "$2a$11$fH/3x26UGR/4LlQrC2xX0e/B/D9fKpha5mGvGO5iAqPhqTYm5DPYC",
                            Role = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 45, 634, DateTimeKind.Utc).AddTicks(9884),
                            Email = "carlos.ruiz@learnconnect.com",
                            FirstName = "Carlos",
                            IsActive = true,
                            LastName = "Ruiz",
                            PasswordHash = "$2a$11$5BxrVprTzivQmvVYAewgnOHdNh6MQ4mzTXY5C3NaPgEEl1XteoxN.",
                            Role = 1
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 45, 859, DateTimeKind.Utc).AddTicks(9240),
                            Email = "isabela.madrigal@learnconnect.com",
                            FirstName = "Isabela",
                            IsActive = true,
                            LastName = "Madrigal",
                            PasswordHash = "$2a$11$gBC7FQsAl4gny7e18TCh1uYNDbo55dyFpg.jRAKjli0iy7GK4jO/e",
                            Role = 1
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 46, 97, DateTimeKind.Utc).AddTicks(7236),
                            Email = "pierre.escargot@learnconnect.com",
                            FirstName = "Pierre",
                            IsActive = true,
                            LastName = "Escargot",
                            PasswordHash = "$2a$11$gSabwkGPLM2YLA6BlYoeXeqb6qQh05ay6kVkPygyMAh8fIHvF7n7C",
                            Role = 1
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 46, 310, DateTimeKind.Utc).AddTicks(9487),
                            Email = "chef.gusteau@learnconnect.com",
                            FirstName = "Auguste",
                            IsActive = true,
                            LastName = "Gusteau",
                            PasswordHash = "$2a$11$tsCc.WZ9d/AOm1cSykNLNeIGuOxEsytfJL7VhBAcmN2V66WZ7qWpW",
                            Role = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 46, 520, DateTimeKind.Utc).AddTicks(2778),
                            Email = "script.kiddie@learnconnect.com",
                            FirstName = "Kevin",
                            IsActive = true,
                            LastName = "Mitnick",
                            PasswordHash = "$2a$11$OxgZYVMxMHh0CsdmG7Ec0eJ42uQYNIKf9LJw4r5F92E.99BtUqJeC",
                            Role = 1
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 46, 711, DateTimeKind.Utc).AddTicks(2470),
                            Email = "dev.ops@learnconnect.com",
                            FirstName = "Linus",
                            IsActive = true,
                            LastName = "Torvalds",
                            PasswordHash = "$2a$11$1kh2GM9Rcx9WIN4hsVkh4ezMSCi8PX2bGcQ/sNZUWIZNWjx4zuVhq",
                            Role = 1
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 46, 890, DateTimeKind.Utc).AddTicks(3617),
                            Email = "ai.researcher@learnconnect.com",
                            FirstName = "Ada",
                            IsActive = true,
                            LastName = "Lovelace",
                            PasswordHash = "$2a$11$KGHW4lERrgxXNzW4GmrJu.3.yaDHYtu99gqzcmbpJgUiCXlcMqT3u",
                            Role = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 47, 68, DateTimeKind.Utc).AddTicks(2267),
                            Email = "time.traveler@learnconnect.com",
                            FirstName = "Marty",
                            IsActive = true,
                            LastName = "McFly",
                            PasswordHash = "$2a$11$jfjn7gxcur8fqB4BGy87rOckPd7NPTRCI0ILQ0Jf/PaDwX6aqiT62",
                            Role = 1
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 47, 246, DateTimeKind.Utc).AddTicks(6931),
                            Email = "museum.guide@learnconnect.com",
                            FirstName = "Indiana",
                            IsActive = true,
                            LastName = "Jones",
                            PasswordHash = "$2a$11$ZBX/LJdEBbjZdUiaxpoY3OdzobkPLWF7BLa.djOHixbvRxpHGTCjm",
                            Role = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 47, 523, DateTimeKind.Utc).AddTicks(2455),
                            Email = "book.worm@learnconnect.com",
                            FirstName = "Hermione",
                            IsActive = true,
                            LastName = "Granger",
                            PasswordHash = "$2a$11$mBghj0CG2.xjOQJQ8pLoIec0HYeuX13h8LRuDDcuqT45QH6wl.XpG",
                            Role = 1
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 47, 739, DateTimeKind.Utc).AddTicks(7407),
                            Email = "published.author@learnconnect.com",
                            FirstName = "J.K.",
                            IsActive = true,
                            LastName = "Rowling",
                            PasswordHash = "$2a$11$y.wGiTiEe7ixgWTIWqOfGu3yWNtLyQi2jO4hcOrJ1akhMCHStJzvm",
                            Role = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 47, 959, DateTimeKind.Utc).AddTicks(2082),
                            Email = "street.performer@learnconnect.com",
                            FirstName = "Ed",
                            IsActive = true,
                            LastName = "Sheeran",
                            PasswordHash = "$2a$11$NBhabJ5rlaeWpFM3zw2sMejGpc4GpND8K0LXLxFyLTrXUulJPaPZ6",
                            Role = 1
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 4, 27, 6, 16, 48, 200, DateTimeKind.Utc).AddTicks(9),
                            Email = "concert.pianist@learnconnect.com",
                            FirstName = "Ludwig",
                            IsActive = true,
                            LastName = "Beethoven",
                            PasswordHash = "$2a$11$/jR9MOZdQrBm3lQc6ZbYmO4ue5M.pyff9Y1s82samvdwnjs1wFKG2",
                            Role = 1
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.Lesson", b =>
                {
                    b.HasOne("LearnConnect.API.Models.LessonPackage", "LessonPackage")
                        .WithMany("Lessons")
                        .HasForeignKey("LessonPackageId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LessonPackage");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonNotebook", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonPackage", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Message", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LearnConnect.API.Models.ParentMeetingRequest", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Payment", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Reservation", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Reservations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Review", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Reviews")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Schedule", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("LearnConnect.API.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnConnect.API.Models.StudentBadge", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Badges")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("LearnConnect.API.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnConnect.API.Models.TeacherSubject", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonPackage", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("LearnConnect.API.Models.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
