// <auto-generated />
using System;
using LearnConnect.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnConnect.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260226084148_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnConnect.API.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonNotebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonNotebooks");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LearnConnect.API.Models.ParentMeetingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ParentMeetingRequests");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLessonDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentUserId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStreak = 0,
                            ExperiencePoints = 0,
                            Level = 1,
                            Location = "New York, USA",
                            PhoneNumber = "+1234567890",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.StudentBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentBadges");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Science",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Science",
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Science",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Science",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Languages",
                            Name = "English"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Languages",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Languages",
                            Name = "French"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Technology",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Technology",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Humanities",
                            Name = "History"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Humanities",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Arts",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Arts",
                            Name = "Piano"
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.7999999999999998,
                            Bio = "Experienced mathematics teacher with 10+ years of teaching experience. Specialized in calculus and algebra.",
                            Education = "PhD in Mathematics, MIT",
                            HourlyRate = 45.00m,
                            Languages = "English,Spanish",
                            Location = "Boston, USA",
                            MemberSince = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567891",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 250,
                            UserId = 3,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 4.9000000000000004,
                            Bio = "Computer Science expert specializing in Python, Java, and web development. Former software engineer at Google.",
                            Education = "MS in Computer Science, Stanford University",
                            HourlyRate = 60.00m,
                            Languages = "English,Mandarin",
                            Location = "San Francisco, USA",
                            MemberSince = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567892",
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 180,
                            UserId = 4,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 4.7000000000000002,
                            Bio = "Native English speaker with TEFL certification. Helping students improve their English communication skills.",
                            Education = "BA in English Literature, Oxford University",
                            HourlyRate = 35.00m,
                            Languages = "English,French",
                            Location = "London, UK",
                            MemberSince = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567893",
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 320,
                            UserId = 5,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2019, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 4.9000000000000004,
                            Bio = "Physics enthusiast with a passion for making complex concepts simple. Specialized in mechanics and electromagnetism.",
                            Education = "PhD in Physics, Caltech",
                            HourlyRate = 50.00m,
                            Languages = "English,Spanish,Portuguese",
                            Location = "Chicago, USA",
                            MemberSince = new DateTime(2018, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567894",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 290,
                            UserId = 6,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2018, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 5.0,
                            Bio = "Professional pianist and music teacher. Teaching piano, music theory, and composition for all levels.",
                            Education = "Master of Music, Juilliard School",
                            HourlyRate = 40.00m,
                            Languages = "English,German,Italian",
                            Location = "Vienna, Austria",
                            MemberSince = new DateTime(2017, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567895",
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 450,
                            UserId = 7,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2017, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 4.5999999999999996,
                            Bio = "Chemistry teacher with expertise in organic and inorganic chemistry. Making chemistry fun and understandable!",
                            Education = "PhD in Chemistry, University of Toronto",
                            HourlyRate = 42.00m,
                            Languages = "English,French",
                            Location = "Toronto, Canada",
                            MemberSince = new DateTime(2020, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567896",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 210,
                            UserId = 8,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 9
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 4.7999999999999998,
                            Bio = "Native Spanish speaker offering conversational Spanish lessons. Learn Spanish the natural way!",
                            Education = "BA in Spanish Linguistics, Universidad Complutense",
                            HourlyRate = 30.00m,
                            Languages = "Spanish,English,Catalan",
                            Location = "Madrid, Spain",
                            MemberSince = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567897",
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 380,
                            UserId = 9,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 4.7000000000000002,
                            Bio = "History professor specializing in World War II and American history. Bringing history to life through engaging storytelling.",
                            Education = "PhD in History, Harvard University",
                            HourlyRate = 38.00m,
                            Languages = "English",
                            Location = "Washington DC, USA",
                            MemberSince = new DateTime(2016, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567898",
                            ResponseTime = "Within 5 hours",
                            TotalLessons = 340,
                            UserId = 10,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2016, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 4.9000000000000004,
                            Bio = "Biology teacher with a focus on molecular biology and genetics. PhD researcher turned educator.",
                            Education = "PhD in Molecular Biology, Cambridge University",
                            HourlyRate = 48.00m,
                            Languages = "English,French",
                            Location = "Cambridge, UK",
                            MemberSince = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567899",
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 195,
                            UserId = 11,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 4.7999999999999998,
                            Bio = "French language expert offering lessons from beginner to advanced. Certified DELF/DALF examiner.",
                            Education = "MA in French Literature, Sorbonne University",
                            HourlyRate = 36.00m,
                            Languages = "French,English,Spanish",
                            Location = "Paris, France",
                            MemberSince = new DateTime(2019, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567800",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 420,
                            UserId = 12,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 11
                        },
                        new
                        {
                            Id = 20,
                            AverageRating = 4.5,
                            Bio = "Math enthusiast helping students love numbers.",
                            Education = "BS Math",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 50,
                            UserId = 20,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 21,
                            AverageRating = 5.0,
                            Bio = "Advanced mathematics for serious students.",
                            Education = "PhD Math",
                            HourlyRate = 75.00m,
                            Languages = "English",
                            Location = "New York",
                            MemberSince = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 500,
                            UserId = 21,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 22,
                            AverageRating = 4.5999999999999996,
                            Bio = "Physics made simple and fun.",
                            Education = "BS Physics",
                            HourlyRate = 28.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 80,
                            UserId = 22,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 23,
                            AverageRating = 4.9000000000000004,
                            Bio = "Expert physics tutoring for university level.",
                            Education = "PhD Physics",
                            HourlyRate = 70.00m,
                            Languages = "English,French",
                            Location = "Paris",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 6 hours",
                            TotalLessons = 300,
                            UserId = 23,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 24,
                            AverageRating = 4.7000000000000002,
                            Bio = "High school chemistry support.",
                            Education = "BS Chemistry",
                            HourlyRate = 30.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 120,
                            UserId = 24,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 25,
                            AverageRating = 5.0,
                            Bio = "Advanced organic chemistry and lab prep.",
                            Education = "PhD Chemistry",
                            HourlyRate = 80.00m,
                            Languages = "English,German",
                            Location = "Berlin",
                            MemberSince = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 24 hours",
                            TotalLessons = 600,
                            UserId = 25,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 25
                        },
                        new
                        {
                            Id = 26,
                            AverageRating = 4.4000000000000004,
                            Bio = "Biology basics for everyone.",
                            Education = "BS Biology",
                            HourlyRate = 22.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 30,
                            UserId = 26,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 27,
                            AverageRating = 4.7999999999999998,
                            Bio = "Genetics and evolutionary biology expert.",
                            Education = "MS Biology",
                            HourlyRate = 45.00m,
                            Languages = "English,German",
                            Location = "Vienna",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 200,
                            UserId = 27,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 28,
                            AverageRating = 4.2999999999999998,
                            Bio = "English conversation and grammar.",
                            Education = "BA English",
                            HourlyRate = 20.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 40,
                            UserId = 28,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 29,
                            AverageRating = 4.9000000000000004,
                            Bio = "Literature analysis and creative writing.",
                            Education = "MFA Writing",
                            HourlyRate = 65.00m,
                            Languages = "English",
                            Location = "London",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 5 hours",
                            TotalLessons = 350,
                            UserId = 29,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 30,
                            AverageRating = 4.7000000000000002,
                            Bio = "Spanish for travel and business.",
                            Education = "BA Spanish",
                            HourlyRate = 40.00m,
                            Languages = "Spanish,English",
                            Location = "Barcelona",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 150,
                            UserId = 30,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 31,
                            AverageRating = 4.9000000000000004,
                            Bio = "Native Spanish speaker, advanced levels.",
                            Education = "MA Linguistics",
                            HourlyRate = 60.00m,
                            Languages = "Spanish,English",
                            Location = "Madrid",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 280,
                            UserId = 31,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 32,
                            AverageRating = 4.5,
                            Bio = "Learn French basics quickly.",
                            Education = "BA French",
                            HourlyRate = 25.00m,
                            Languages = "French,English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 60,
                            UserId = 32,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 33,
                            AverageRating = 5.0,
                            Bio = "Master French cuisine and language.",
                            Education = "Culinary Arts",
                            HourlyRate = 70.00m,
                            Languages = "French,English",
                            Location = "Paris",
                            MemberSince = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 8 hours",
                            TotalLessons = 400,
                            UserId = 33,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 34,
                            AverageRating = 4.5999999999999996,
                            Bio = "Intro to coding and cybersecurity.",
                            Education = "Self-taught",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 90,
                            UserId = 34,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 35,
                            AverageRating = 4.7999999999999998,
                            Bio = "DevOps, Linux, and System Admin.",
                            Education = "MS CS",
                            HourlyRate = 55.00m,
                            Languages = "English,Finnish",
                            Location = "Helsinki",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 220,
                            UserId = 35,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 36,
                            AverageRating = 5.0,
                            Bio = "Artificial Intelligence and Machine Learning.",
                            Education = "PhD CS",
                            HourlyRate = 90.00m,
                            Languages = "English",
                            Location = "San Francisco",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 180,
                            UserId = 36,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 37,
                            AverageRating = 4.4000000000000004,
                            Bio = "History through the ages.",
                            Education = "BA History",
                            HourlyRate = 20.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 45,
                            UserId = 37,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 38,
                            AverageRating = 4.7999999999999998,
                            Bio = "Archaeology and ancient civilizations.",
                            Education = "PhD Archaeology",
                            HourlyRate = 40.00m,
                            Languages = "English",
                            Location = "Cairo",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 6 hours",
                            TotalLessons = 300,
                            UserId = 38,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 39,
                            AverageRating = 4.7000000000000002,
                            Bio = "Reading comprehension and book clubs.",
                            Education = "BA Lit",
                            HourlyRate = 22.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 100,
                            UserId = 39,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 40,
                            AverageRating = 4.9000000000000004,
                            Bio = "Creative writing masterclass.",
                            Education = "BA Classics",
                            HourlyRate = 65.00m,
                            Languages = "English",
                            Location = "Edinburgh",
                            MemberSince = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 24 hours",
                            TotalLessons = 500,
                            UserId = 40,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 41,
                            AverageRating = 4.7999999999999998,
                            Bio = "Guitar and pop music basics.",
                            Education = "Self-taught",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "London",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 150,
                            UserId = 41,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 42,
                            AverageRating = 5.0,
                            Bio = "Classical piano and composition.",
                            Education = "Conservatory",
                            HourlyRate = 85.00m,
                            Languages = "German,English",
                            Location = "Vienna",
                            MemberSince = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 800,
                            UserId = 42,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2018, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 30
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            SubjectId = 8,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            SubjectId = 9,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            SubjectId = 5,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 5,
                            SubjectId = 11,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 6,
                            SubjectId = 2,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 7,
                            SubjectId = 12,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 8,
                            SubjectId = 13,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 9,
                            SubjectId = 3,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 10,
                            SubjectId = 6,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 11,
                            SubjectId = 10,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 12,
                            SubjectId = 4,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 13,
                            SubjectId = 7,
                            TeacherId = 10
                        },
                        new
                        {
                            Id = 14,
                            SubjectId = 11,
                            TeacherId = 10
                        },
                        new
                        {
                            Id = 20,
                            SubjectId = 1,
                            TeacherId = 20
                        },
                        new
                        {
                            Id = 21,
                            SubjectId = 1,
                            TeacherId = 21
                        },
                        new
                        {
                            Id = 22,
                            SubjectId = 2,
                            TeacherId = 22
                        },
                        new
                        {
                            Id = 23,
                            SubjectId = 2,
                            TeacherId = 23
                        },
                        new
                        {
                            Id = 24,
                            SubjectId = 3,
                            TeacherId = 24
                        },
                        new
                        {
                            Id = 25,
                            SubjectId = 3,
                            TeacherId = 25
                        },
                        new
                        {
                            Id = 26,
                            SubjectId = 4,
                            TeacherId = 26
                        },
                        new
                        {
                            Id = 27,
                            SubjectId = 4,
                            TeacherId = 27
                        },
                        new
                        {
                            Id = 28,
                            SubjectId = 5,
                            TeacherId = 28
                        },
                        new
                        {
                            Id = 29,
                            SubjectId = 5,
                            TeacherId = 29
                        },
                        new
                        {
                            Id = 30,
                            SubjectId = 6,
                            TeacherId = 30
                        },
                        new
                        {
                            Id = 31,
                            SubjectId = 6,
                            TeacherId = 31
                        },
                        new
                        {
                            Id = 32,
                            SubjectId = 7,
                            TeacherId = 32
                        },
                        new
                        {
                            Id = 33,
                            SubjectId = 7,
                            TeacherId = 33
                        },
                        new
                        {
                            Id = 34,
                            SubjectId = 8,
                            TeacherId = 34
                        },
                        new
                        {
                            Id = 35,
                            SubjectId = 9,
                            TeacherId = 34
                        },
                        new
                        {
                            Id = 36,
                            SubjectId = 8,
                            TeacherId = 35
                        },
                        new
                        {
                            Id = 37,
                            SubjectId = 9,
                            TeacherId = 35
                        },
                        new
                        {
                            Id = 38,
                            SubjectId = 8,
                            TeacherId = 36
                        },
                        new
                        {
                            Id = 39,
                            SubjectId = 9,
                            TeacherId = 36
                        },
                        new
                        {
                            Id = 40,
                            SubjectId = 10,
                            TeacherId = 37
                        },
                        new
                        {
                            Id = 41,
                            SubjectId = 10,
                            TeacherId = 38
                        },
                        new
                        {
                            Id = 42,
                            SubjectId = 11,
                            TeacherId = 39
                        },
                        new
                        {
                            Id = 43,
                            SubjectId = 11,
                            TeacherId = 40
                        },
                        new
                        {
                            Id = 44,
                            SubjectId = 12,
                            TeacherId = 41
                        },
                        new
                        {
                            Id = 45,
                            SubjectId = 13,
                            TeacherId = 41
                        },
                        new
                        {
                            Id = 46,
                            SubjectId = 12,
                            TeacherId = 42
                        },
                        new
                        {
                            Id = 47,
                            SubjectId = 13,
                            TeacherId = 42
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 39, 721, DateTimeKind.Utc).AddTicks(5393),
                            Email = "admin@learnconnect.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$o05GVdsdThXmsIcK26bvHe0rVj.UFyI0KuuRLajSvoaaMyrLoqwGC",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 39, 934, DateTimeKind.Utc).AddTicks(484),
                            Email = "student@test.com",
                            FirstName = "Test",
                            IsActive = true,
                            LastName = "Student",
                            PasswordHash = "$2a$11$RYCxzT9nDuGRFydE8Rrcj.TJY5QsZODcTCTybzShhPhVP2/PKBxLK",
                            Role = 0
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 40, 177, DateTimeKind.Utc).AddTicks(6108),
                            Email = "parent@test.com",
                            FirstName = "Test",
                            IsActive = true,
                            LastName = "Parent",
                            PasswordHash = "$2a$11$Sky1vCjyAJqdAa77x406HuEPk/yCmDXkLJFItRd8dLbZ1yThx/Gey",
                            Role = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 40, 384, DateTimeKind.Utc).AddTicks(2275),
                            Email = "sarah.johnson@learnconnect.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$rwLPymy5/nLX6GIqYbewGOSIHn4chqUeW3Ub8/l5sGXcM9mXSSmy6",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 40, 623, DateTimeKind.Utc).AddTicks(7364),
                            Email = "michael.chen@learnconnect.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Chen",
                            PasswordHash = "$2a$11$ybu3WyaClQC5oTR4Sl5VPOEkuW1vsCxIR.LE3kK33.8QTfO0rCSW6",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 40, 923, DateTimeKind.Utc).AddTicks(1336),
                            Email = "emma.davis@learnconnect.com",
                            FirstName = "Emma",
                            IsActive = true,
                            LastName = "Davis",
                            PasswordHash = "$2a$11$IPU5xF5j/hlwrqcxlY4cvOs0XrkL3ROfKjrX7xsBwJ35arUKgl/GW",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 41, 157, DateTimeKind.Utc).AddTicks(3448),
                            Email = "david.martinez@learnconnect.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Martinez",
                            PasswordHash = "$2a$11$wI9M.DwjaZuXaGFE7vUz/On1mN.LBehQZaLRsjZhEO4uOXXl35/am",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 41, 451, DateTimeKind.Utc).AddTicks(1181),
                            Email = "lisa.anderson@learnconnect.com",
                            FirstName = "Lisa",
                            IsActive = true,
                            LastName = "Anderson",
                            PasswordHash = "$2a$11$2Cfh.p4pNMXwyhFP6EPsDe6nKkINBw9DWFAf.ValsYzBycFjI7RxS",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 41, 691, DateTimeKind.Utc).AddTicks(8244),
                            Email = "james.wilson@learnconnect.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Wilson",
                            PasswordHash = "$2a$11$BQZ82pp/..yLITKaHVHgAeEayO6uGk0hMlG5K3b41fSlomsVl7Cm6",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 41, 929, DateTimeKind.Utc).AddTicks(1397),
                            Email = "sophia.garcia@learnconnect.com",
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Garcia",
                            PasswordHash = "$2a$11$2tUvzRh6smu73bfDmaC4..d5ZcdFk3QvNm1FVzKHw00GVk9yP89zK",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 42, 89, DateTimeKind.Utc).AddTicks(5014),
                            Email = "robert.brown@learnconnect.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Brown",
                            PasswordHash = "$2a$11$nKdbnMdB2iUzf4W9th4foel/puyYs1IjIIQLBN7rQn32cDbjm3AsC",
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 42, 280, DateTimeKind.Utc).AddTicks(2871),
                            Email = "olivia.taylor@learnconnect.com",
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Taylor",
                            PasswordHash = "$2a$11$t3fkQqvHNtKVEAy6eesleOWSA1rOhHqGfWGQy2M3Uf9fSaApN3saO",
                            Role = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 42, 443, DateTimeKind.Utc).AddTicks(7453),
                            Email = "daniel.moore@learnconnect.com",
                            FirstName = "Daniel",
                            IsActive = true,
                            LastName = "Moore",
                            PasswordHash = "$2a$11$aZw3zZ628E7UL0su0OZDEO3tQX6L0.QV2DMY9t54ZMfrR8hRDfcxm",
                            Role = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 42, 630, DateTimeKind.Utc).AddTicks(4226),
                            Email = "alice.walker@learnconnect.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Walker",
                            PasswordHash = "$2a$11$oZViqyN8hO0HhDEKPz65XORrPyxWiPZyU4alUDa2rCzLXQ1QNmYrO",
                            Role = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 42, 791, DateTimeKind.Utc).AddTicks(7481),
                            Email = "robert.vance@learnconnect.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Vance",
                            PasswordHash = "$2a$11$lWQoDoeLAkNKZEhgkXI4FuJoD3RKX2lj3R4gnYaIajgZU77whDPou",
                            Role = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 42, 975, DateTimeKind.Utc).AddTicks(5542),
                            Email = "john.doe@learnconnect.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$cMykedgIuxyVlHkEWr1GPeY6cy9x9gSbGWIb0M30oyfCZ4Vt4HU46",
                            Role = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 43, 138, DateTimeKind.Utc).AddTicks(9834),
                            Email = "marie.curie@learnconnect.com",
                            FirstName = "Marie",
                            IsActive = true,
                            LastName = "Curie",
                            PasswordHash = "$2a$11$rc.aXpJkaBeIfFgwPZgv9OeYQrjNs3X3feAfTFoJAAyuBb96r69I.",
                            Role = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 43, 366, DateTimeKind.Utc).AddTicks(8933),
                            Email = "walter.white@learnconnect.com",
                            FirstName = "Walter",
                            IsActive = true,
                            LastName = "White",
                            PasswordHash = "$2a$11$UGLYTLUT6ksWbgqZFiLcHOW4rYFErrDMV5sXfO/zZ9hXaG1Swl1hC",
                            Role = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 43, 525, DateTimeKind.Utc).AddTicks(6720),
                            Email = "heisenberg@learnconnect.com",
                            FirstName = "Werner",
                            IsActive = true,
                            LastName = "Heisenberg",
                            PasswordHash = "$2a$11$wmJS9ni6r.O2XSVkNkvLNeS/3laRcf0928aGFG.AvGyLGn.EnpdS6",
                            Role = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 43, 790, DateTimeKind.Utc).AddTicks(1953),
                            Email = "jane.goodall@learnconnect.com",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Goodall",
                            PasswordHash = "$2a$11$p5FL4Lqn8aivwe44ALwRc.SAdJGhdvWiwaHtObcxde4y0N4VJayRm",
                            Role = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 43, 980, DateTimeKind.Utc).AddTicks(9971),
                            Email = "gregor.mendel@learnconnect.com",
                            FirstName = "Gregor",
                            IsActive = true,
                            LastName = "Mendel",
                            PasswordHash = "$2a$11$XEVczyR8X9b6ymKX3TTBWOk0s0dLDH5Yj1azZCBbHHpxWYwJ8.A7S",
                            Role = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 44, 292, DateTimeKind.Utc).AddTicks(9777),
                            Email = "new.grad@learnconnect.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Dickinson",
                            PasswordHash = "$2a$11$VAZDCP7O6xBuAdeV0.u2OORRcJSzFz7jjFzSs0z1mK28H9RlZUz4q",
                            Role = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 44, 502, DateTimeKind.Utc).AddTicks(7092),
                            Email = "shakespeare@learnconnect.com",
                            FirstName = "William",
                            IsActive = true,
                            LastName = "Shakespeare",
                            PasswordHash = "$2a$11$pTo.xI9ax30l7Dx74QN/o.1FWu5FPMUw.Sj8RXkxJ0sbaijDEEUAK",
                            Role = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 44, 663, DateTimeKind.Utc).AddTicks(1082),
                            Email = "carlos.ruiz@learnconnect.com",
                            FirstName = "Carlos",
                            IsActive = true,
                            LastName = "Ruiz",
                            PasswordHash = "$2a$11$40g0va.uWMuWfaiqQr4pkuY73xk3h3PqSCIRe1ikk6DdsVJn7/5HC",
                            Role = 1
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 44, 841, DateTimeKind.Utc).AddTicks(6071),
                            Email = "isabela.madrigal@learnconnect.com",
                            FirstName = "Isabela",
                            IsActive = true,
                            LastName = "Madrigal",
                            PasswordHash = "$2a$11$5yydyXC7ssx7takPDmVjYuBse2EahTgB1KQ.s18JUj5cDko4l0uBi",
                            Role = 1
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 45, 10, DateTimeKind.Utc).AddTicks(7250),
                            Email = "pierre.escargot@learnconnect.com",
                            FirstName = "Pierre",
                            IsActive = true,
                            LastName = "Escargot",
                            PasswordHash = "$2a$11$ANm.ARSJg6AurkLKJC63H.N6oeR3FBHhmw3ASP8hau3hWA898XZcC",
                            Role = 1
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 45, 175, DateTimeKind.Utc).AddTicks(3863),
                            Email = "chef.gusteau@learnconnect.com",
                            FirstName = "Auguste",
                            IsActive = true,
                            LastName = "Gusteau",
                            PasswordHash = "$2a$11$VupLELbXd1l.AvoRYlPwde80.dWGiaSNVTdg3k0Ac6WtLhuwqvn0C",
                            Role = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 45, 428, DateTimeKind.Utc).AddTicks(8845),
                            Email = "script.kiddie@learnconnect.com",
                            FirstName = "Kevin",
                            IsActive = true,
                            LastName = "Mitnick",
                            PasswordHash = "$2a$11$eowmstJOr11ETd7FlUkPt.LdKDsbypmqiDWRvUIybgOeK1YyHWPzu",
                            Role = 1
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 45, 723, DateTimeKind.Utc).AddTicks(8854),
                            Email = "dev.ops@learnconnect.com",
                            FirstName = "Linus",
                            IsActive = true,
                            LastName = "Torvalds",
                            PasswordHash = "$2a$11$hZl5dRdewj67uvpVkrUjGuP3qfUkIIkHVgeoxHFKjJlOJ29FDlGfa",
                            Role = 1
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 45, 961, DateTimeKind.Utc).AddTicks(1650),
                            Email = "ai.researcher@learnconnect.com",
                            FirstName = "Ada",
                            IsActive = true,
                            LastName = "Lovelace",
                            PasswordHash = "$2a$11$0Xb3dgsv0jA2UL9DSii7xeiVRw.vBzfMbZetM5icZCpkX9V/Curve",
                            Role = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 46, 160, DateTimeKind.Utc).AddTicks(9166),
                            Email = "time.traveler@learnconnect.com",
                            FirstName = "Marty",
                            IsActive = true,
                            LastName = "McFly",
                            PasswordHash = "$2a$11$d.rDmU7o1Rh3FVLW7C9CGeOGFfKl38jBAHrSgdaWhzndzD2VUKdYm",
                            Role = 1
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 46, 365, DateTimeKind.Utc).AddTicks(346),
                            Email = "museum.guide@learnconnect.com",
                            FirstName = "Indiana",
                            IsActive = true,
                            LastName = "Jones",
                            PasswordHash = "$2a$11$uVhvmTmMMT8qoPW39BRcW.Ugdkl9QyHP67l8t0TksJgZtkxYQ74fG",
                            Role = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 46, 575, DateTimeKind.Utc).AddTicks(4972),
                            Email = "book.worm@learnconnect.com",
                            FirstName = "Hermione",
                            IsActive = true,
                            LastName = "Granger",
                            PasswordHash = "$2a$11$ee6KlPgnoK.uS9GGsWY2Hez01rbGsvwA7KTvnywqkbmHugT3hKJEG",
                            Role = 1
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 46, 852, DateTimeKind.Utc).AddTicks(2628),
                            Email = "published.author@learnconnect.com",
                            FirstName = "J.K.",
                            IsActive = true,
                            LastName = "Rowling",
                            PasswordHash = "$2a$11$FujJ..O.vYlxIHA0P7LMEuVpDkJxYv/cW4ypjUN7ga7MubPSUtG/q",
                            Role = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 47, 79, DateTimeKind.Utc).AddTicks(3074),
                            Email = "street.performer@learnconnect.com",
                            FirstName = "Ed",
                            IsActive = true,
                            LastName = "Sheeran",
                            PasswordHash = "$2a$11$620ggWZ7RzSLEnGeGA41Wep9oOdpb/LPXUo1Sdk/Uc56btXp5V00K",
                            Role = 1
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 2, 26, 8, 41, 47, 402, DateTimeKind.Utc).AddTicks(3728),
                            Email = "concert.pianist@learnconnect.com",
                            FirstName = "Ludwig",
                            IsActive = true,
                            LastName = "Beethoven",
                            PasswordHash = "$2a$11$RmH1CeUY.Aus.aY1YEo1k.rw7Gwn0GKaXvYgQY9MYp50sC1AiVAE.",
                            Role = 1
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.Lesson", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonNotebook", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Message", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LearnConnect.API.Models.ParentMeetingRequest", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Reservation", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Reservations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Review", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Reviews")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Schedule", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("LearnConnect.API.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnConnect.API.Models.StudentBadge", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Badges")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("LearnConnect.API.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnConnect.API.Models.TeacherSubject", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("LearnConnect.API.Models.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
