// <auto-generated />
using System;
using LearnConnect.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LearnConnect.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LearnConnect.API.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonNotebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonNotebooks");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LearnConnect.API.Models.ParentMeetingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ParentMeetingRequests");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Method")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLessonDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentUserId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStreak = 0,
                            ExperiencePoints = 0,
                            Level = 1,
                            Location = "New York, USA",
                            PhoneNumber = "+1234567890",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.StudentBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentBadges");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Science",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Science",
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Science",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Science",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Languages",
                            Name = "English"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Languages",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Languages",
                            Name = "French"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Technology",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Technology",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Humanities",
                            Name = "History"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Humanities",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Arts",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Arts",
                            Name = "Piano"
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("float");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Languages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MemberSince")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.7999999999999998,
                            Bio = "Experienced mathematics teacher with 10+ years of teaching experience. Specialized in calculus and algebra.",
                            Education = "PhD in Mathematics, MIT",
                            HourlyRate = 45.00m,
                            Languages = "English,Spanish",
                            Location = "Boston, USA",
                            MemberSince = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567891",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 250,
                            UserId = 3,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 4.9000000000000004,
                            Bio = "Computer Science expert specializing in Python, Java, and web development. Former software engineer at Google.",
                            Education = "MS in Computer Science, Stanford University",
                            HourlyRate = 60.00m,
                            Languages = "English,Mandarin",
                            Location = "San Francisco, USA",
                            MemberSince = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567892",
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 180,
                            UserId = 4,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 4.7000000000000002,
                            Bio = "Native English speaker with TEFL certification. Helping students improve their English communication skills.",
                            Education = "BA in English Literature, Oxford University",
                            HourlyRate = 35.00m,
                            Languages = "English,French",
                            Location = "London, UK",
                            MemberSince = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567893",
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 320,
                            UserId = 5,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2019, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 4.9000000000000004,
                            Bio = "Physics enthusiast with a passion for making complex concepts simple. Specialized in mechanics and electromagnetism.",
                            Education = "PhD in Physics, Caltech",
                            HourlyRate = 50.00m,
                            Languages = "English,Spanish,Portuguese",
                            Location = "Chicago, USA",
                            MemberSince = new DateTime(2018, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567894",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 290,
                            UserId = 6,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2018, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 5.0,
                            Bio = "Professional pianist and music teacher. Teaching piano, music theory, and composition for all levels.",
                            Education = "Master of Music, Juilliard School",
                            HourlyRate = 40.00m,
                            Languages = "English,German,Italian",
                            Location = "Vienna, Austria",
                            MemberSince = new DateTime(2017, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567895",
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 450,
                            UserId = 7,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2017, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 4.5999999999999996,
                            Bio = "Chemistry teacher with expertise in organic and inorganic chemistry. Making chemistry fun and understandable!",
                            Education = "PhD in Chemistry, University of Toronto",
                            HourlyRate = 42.00m,
                            Languages = "English,French",
                            Location = "Toronto, Canada",
                            MemberSince = new DateTime(2020, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567896",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 210,
                            UserId = 8,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 9
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 4.7999999999999998,
                            Bio = "Native Spanish speaker offering conversational Spanish lessons. Learn Spanish the natural way!",
                            Education = "BA in Spanish Linguistics, Universidad Complutense",
                            HourlyRate = 30.00m,
                            Languages = "Spanish,English,Catalan",
                            Location = "Madrid, Spain",
                            MemberSince = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567897",
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 380,
                            UserId = 9,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 4.7000000000000002,
                            Bio = "History professor specializing in World War II and American history. Bringing history to life through engaging storytelling.",
                            Education = "PhD in History, Harvard University",
                            HourlyRate = 38.00m,
                            Languages = "English",
                            Location = "Washington DC, USA",
                            MemberSince = new DateTime(2016, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567898",
                            ResponseTime = "Within 5 hours",
                            TotalLessons = 340,
                            UserId = 10,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2016, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 4.9000000000000004,
                            Bio = "Biology teacher with a focus on molecular biology and genetics. PhD researcher turned educator.",
                            Education = "PhD in Molecular Biology, Cambridge University",
                            HourlyRate = 48.00m,
                            Languages = "English,French",
                            Location = "Cambridge, UK",
                            MemberSince = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567899",
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 195,
                            UserId = 11,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 4.7999999999999998,
                            Bio = "French language expert offering lessons from beginner to advanced. Certified DELF/DALF examiner.",
                            Education = "MA in French Literature, Sorbonne University",
                            HourlyRate = 36.00m,
                            Languages = "French,English,Spanish",
                            Location = "Paris, France",
                            MemberSince = new DateTime(2019, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567800",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 420,
                            UserId = 12,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 11
                        },
                        new
                        {
                            Id = 20,
                            AverageRating = 4.5,
                            Bio = "Math enthusiast helping students love numbers.",
                            Education = "BS Math",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 50,
                            UserId = 20,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 21,
                            AverageRating = 5.0,
                            Bio = "Advanced mathematics for serious students.",
                            Education = "PhD Math",
                            HourlyRate = 75.00m,
                            Languages = "English",
                            Location = "New York",
                            MemberSince = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 500,
                            UserId = 21,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 22,
                            AverageRating = 4.5999999999999996,
                            Bio = "Physics made simple and fun.",
                            Education = "BS Physics",
                            HourlyRate = 28.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 80,
                            UserId = 22,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 23,
                            AverageRating = 4.9000000000000004,
                            Bio = "Expert physics tutoring for university level.",
                            Education = "PhD Physics",
                            HourlyRate = 70.00m,
                            Languages = "English,French",
                            Location = "Paris",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 6 hours",
                            TotalLessons = 300,
                            UserId = 23,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 24,
                            AverageRating = 4.7000000000000002,
                            Bio = "High school chemistry support.",
                            Education = "BS Chemistry",
                            HourlyRate = 30.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 120,
                            UserId = 24,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 25,
                            AverageRating = 5.0,
                            Bio = "Advanced organic chemistry and lab prep.",
                            Education = "PhD Chemistry",
                            HourlyRate = 80.00m,
                            Languages = "English,German",
                            Location = "Berlin",
                            MemberSince = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 24 hours",
                            TotalLessons = 600,
                            UserId = 25,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 25
                        },
                        new
                        {
                            Id = 26,
                            AverageRating = 4.4000000000000004,
                            Bio = "Biology basics for everyone.",
                            Education = "BS Biology",
                            HourlyRate = 22.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 30,
                            UserId = 26,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 27,
                            AverageRating = 4.7999999999999998,
                            Bio = "Genetics and evolutionary biology expert.",
                            Education = "MS Biology",
                            HourlyRate = 45.00m,
                            Languages = "English,German",
                            Location = "Vienna",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 200,
                            UserId = 27,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 28,
                            AverageRating = 4.2999999999999998,
                            Bio = "English conversation and grammar.",
                            Education = "BA English",
                            HourlyRate = 20.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 40,
                            UserId = 28,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 29,
                            AverageRating = 4.9000000000000004,
                            Bio = "Literature analysis and creative writing.",
                            Education = "MFA Writing",
                            HourlyRate = 65.00m,
                            Languages = "English",
                            Location = "London",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 5 hours",
                            TotalLessons = 350,
                            UserId = 29,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 30,
                            AverageRating = 4.7000000000000002,
                            Bio = "Spanish for travel and business.",
                            Education = "BA Spanish",
                            HourlyRate = 40.00m,
                            Languages = "Spanish,English",
                            Location = "Barcelona",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 150,
                            UserId = 30,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 31,
                            AverageRating = 4.9000000000000004,
                            Bio = "Native Spanish speaker, advanced levels.",
                            Education = "MA Linguistics",
                            HourlyRate = 60.00m,
                            Languages = "Spanish,English",
                            Location = "Madrid",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 280,
                            UserId = 31,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 32,
                            AverageRating = 4.5,
                            Bio = "Learn French basics quickly.",
                            Education = "BA French",
                            HourlyRate = 25.00m,
                            Languages = "French,English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 60,
                            UserId = 32,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 33,
                            AverageRating = 5.0,
                            Bio = "Master French cuisine and language.",
                            Education = "Culinary Arts",
                            HourlyRate = 70.00m,
                            Languages = "French,English",
                            Location = "Paris",
                            MemberSince = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 8 hours",
                            TotalLessons = 400,
                            UserId = 33,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 34,
                            AverageRating = 4.5999999999999996,
                            Bio = "Intro to coding and cybersecurity.",
                            Education = "Self-taught",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 90,
                            UserId = 34,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 35,
                            AverageRating = 4.7999999999999998,
                            Bio = "DevOps, Linux, and System Admin.",
                            Education = "MS CS",
                            HourlyRate = 55.00m,
                            Languages = "English,Finnish",
                            Location = "Helsinki",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 220,
                            UserId = 35,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 36,
                            AverageRating = 5.0,
                            Bio = "Artificial Intelligence and Machine Learning.",
                            Education = "PhD CS",
                            HourlyRate = 90.00m,
                            Languages = "English",
                            Location = "San Francisco",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 180,
                            UserId = 36,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 37,
                            AverageRating = 4.4000000000000004,
                            Bio = "History through the ages.",
                            Education = "BA History",
                            HourlyRate = 20.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 45,
                            UserId = 37,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 38,
                            AverageRating = 4.7999999999999998,
                            Bio = "Archaeology and ancient civilizations.",
                            Education = "PhD Archaeology",
                            HourlyRate = 40.00m,
                            Languages = "English",
                            Location = "Cairo",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 6 hours",
                            TotalLessons = 300,
                            UserId = 38,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 39,
                            AverageRating = 4.7000000000000002,
                            Bio = "Reading comprehension and book clubs.",
                            Education = "BA Lit",
                            HourlyRate = 22.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 100,
                            UserId = 39,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 40,
                            AverageRating = 4.9000000000000004,
                            Bio = "Creative writing masterclass.",
                            Education = "BA Classics",
                            HourlyRate = 65.00m,
                            Languages = "English",
                            Location = "Edinburgh",
                            MemberSince = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 24 hours",
                            TotalLessons = 500,
                            UserId = 40,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 41,
                            AverageRating = 4.7999999999999998,
                            Bio = "Guitar and pop music basics.",
                            Education = "Self-taught",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "London",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 150,
                            UserId = 41,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 42,
                            AverageRating = 5.0,
                            Bio = "Classical piano and composition.",
                            Education = "Conservatory",
                            HourlyRate = 85.00m,
                            Languages = "German,English",
                            Location = "Vienna",
                            MemberSince = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 800,
                            UserId = 42,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2018, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 30
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            SubjectId = 8,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            SubjectId = 9,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            SubjectId = 5,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 5,
                            SubjectId = 11,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 6,
                            SubjectId = 2,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 7,
                            SubjectId = 12,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 8,
                            SubjectId = 13,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 9,
                            SubjectId = 3,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 10,
                            SubjectId = 6,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 11,
                            SubjectId = 10,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 12,
                            SubjectId = 4,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 13,
                            SubjectId = 7,
                            TeacherId = 10
                        },
                        new
                        {
                            Id = 14,
                            SubjectId = 11,
                            TeacherId = 10
                        },
                        new
                        {
                            Id = 20,
                            SubjectId = 1,
                            TeacherId = 20
                        },
                        new
                        {
                            Id = 21,
                            SubjectId = 1,
                            TeacherId = 21
                        },
                        new
                        {
                            Id = 22,
                            SubjectId = 2,
                            TeacherId = 22
                        },
                        new
                        {
                            Id = 23,
                            SubjectId = 2,
                            TeacherId = 23
                        },
                        new
                        {
                            Id = 24,
                            SubjectId = 3,
                            TeacherId = 24
                        },
                        new
                        {
                            Id = 25,
                            SubjectId = 3,
                            TeacherId = 25
                        },
                        new
                        {
                            Id = 26,
                            SubjectId = 4,
                            TeacherId = 26
                        },
                        new
                        {
                            Id = 27,
                            SubjectId = 4,
                            TeacherId = 27
                        },
                        new
                        {
                            Id = 28,
                            SubjectId = 5,
                            TeacherId = 28
                        },
                        new
                        {
                            Id = 29,
                            SubjectId = 5,
                            TeacherId = 29
                        },
                        new
                        {
                            Id = 30,
                            SubjectId = 6,
                            TeacherId = 30
                        },
                        new
                        {
                            Id = 31,
                            SubjectId = 6,
                            TeacherId = 31
                        },
                        new
                        {
                            Id = 32,
                            SubjectId = 7,
                            TeacherId = 32
                        },
                        new
                        {
                            Id = 33,
                            SubjectId = 7,
                            TeacherId = 33
                        },
                        new
                        {
                            Id = 34,
                            SubjectId = 8,
                            TeacherId = 34
                        },
                        new
                        {
                            Id = 35,
                            SubjectId = 9,
                            TeacherId = 34
                        },
                        new
                        {
                            Id = 36,
                            SubjectId = 8,
                            TeacherId = 35
                        },
                        new
                        {
                            Id = 37,
                            SubjectId = 9,
                            TeacherId = 35
                        },
                        new
                        {
                            Id = 38,
                            SubjectId = 8,
                            TeacherId = 36
                        },
                        new
                        {
                            Id = 39,
                            SubjectId = 9,
                            TeacherId = 36
                        },
                        new
                        {
                            Id = 40,
                            SubjectId = 10,
                            TeacherId = 37
                        },
                        new
                        {
                            Id = 41,
                            SubjectId = 10,
                            TeacherId = 38
                        },
                        new
                        {
                            Id = 42,
                            SubjectId = 11,
                            TeacherId = 39
                        },
                        new
                        {
                            Id = 43,
                            SubjectId = 11,
                            TeacherId = 40
                        },
                        new
                        {
                            Id = 44,
                            SubjectId = 12,
                            TeacherId = 41
                        },
                        new
                        {
                            Id = 45,
                            SubjectId = 13,
                            TeacherId = 41
                        },
                        new
                        {
                            Id = 46,
                            SubjectId = 12,
                            TeacherId = 42
                        },
                        new
                        {
                            Id = 47,
                            SubjectId = 13,
                            TeacherId = 42
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 26, 59, 532, DateTimeKind.Utc).AddTicks(2553),
                            Email = "admin@learnconnect.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$0eMDP.67Qv5QelJtomEOpOuR6SXvlVdHyDBMfnOLNxkUFx0WMA0Ka",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 26, 59, 898, DateTimeKind.Utc).AddTicks(9363),
                            Email = "student@test.com",
                            FirstName = "Test",
                            IsActive = true,
                            LastName = "Student",
                            PasswordHash = "$2a$11$KyPhg159sn2A3iPtggsRqOG4Ytpdxc8WE8a4JAhAK0dE/4klxC/4y",
                            Role = 0
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 0, 228, DateTimeKind.Utc).AddTicks(6249),
                            Email = "parent@test.com",
                            FirstName = "Test",
                            IsActive = true,
                            LastName = "Parent",
                            PasswordHash = "$2a$11$v/L3pPAcSAlcJiI3DHl89elY0Qr5qIuxHs1XH5xLnu9ySSTIVq1Uu",
                            Role = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 0, 743, DateTimeKind.Utc).AddTicks(6929),
                            Email = "sarah.johnson@learnconnect.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$GP1sPUdeLXqZkLPb8082AO39mZi8sMEAJX/qn.pI5ayIwg9qFKlS.",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 1, 217, DateTimeKind.Utc).AddTicks(7509),
                            Email = "michael.chen@learnconnect.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Chen",
                            PasswordHash = "$2a$11$x4cKDkJHwrqxIChmeECrkeLLUQskLMHZpvrAmyGOdV9/qxfppdrsK",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 1, 661, DateTimeKind.Utc).AddTicks(2594),
                            Email = "emma.davis@learnconnect.com",
                            FirstName = "Emma",
                            IsActive = true,
                            LastName = "Davis",
                            PasswordHash = "$2a$11$lHfugm66S8BEXzrNjvKoH.EZDI6IQMtmOw1geVGUvU7234JvsvRBC",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 2, 58, DateTimeKind.Utc).AddTicks(8218),
                            Email = "david.martinez@learnconnect.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Martinez",
                            PasswordHash = "$2a$11$eYiO6hYOfichkAsgVApPNe4bofElaSQNXbM8zNZoFYMpBG4Ge/VhO",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 3, 257, DateTimeKind.Utc).AddTicks(8342),
                            Email = "lisa.anderson@learnconnect.com",
                            FirstName = "Lisa",
                            IsActive = true,
                            LastName = "Anderson",
                            PasswordHash = "$2a$11$OEIb/B8SgnZ4sqBDXnLf9.WiMqjuuDxBxQ8k9AoMqSt.GqDU.WDuS",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 3, 645, DateTimeKind.Utc).AddTicks(1894),
                            Email = "james.wilson@learnconnect.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Wilson",
                            PasswordHash = "$2a$11$dQMwzKK8jSDeKBe9DDJ5hunPcA.YY4XY/E6PUlalBJU4WwquW2M6m",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 3, 990, DateTimeKind.Utc).AddTicks(6281),
                            Email = "sophia.garcia@learnconnect.com",
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Garcia",
                            PasswordHash = "$2a$11$f2DihjqX.avDL.8.Sa9.d.dkJh6YtM.MCoiHgEoUls7AplJUl6UPe",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 4, 317, DateTimeKind.Utc).AddTicks(7288),
                            Email = "robert.brown@learnconnect.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Brown",
                            PasswordHash = "$2a$11$lOdCDBuVT3ZBXTc.y/JbPuF9YrYYYwdW.SLesaosiVDISLBkY/TaO",
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 4, 647, DateTimeKind.Utc).AddTicks(3631),
                            Email = "olivia.taylor@learnconnect.com",
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Taylor",
                            PasswordHash = "$2a$11$dIzoounLVjLmk6u3mRM2heErYzZ0RfByDDfFTy9aZZZAYu62XhUk2",
                            Role = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 4, 968, DateTimeKind.Utc).AddTicks(6585),
                            Email = "daniel.moore@learnconnect.com",
                            FirstName = "Daniel",
                            IsActive = true,
                            LastName = "Moore",
                            PasswordHash = "$2a$11$7VacmbYiwfPYV1Ims0umpue5wj2f/v9UG6LfwisI1v0gI6KVf4pyq",
                            Role = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 5, 190, DateTimeKind.Utc).AddTicks(7564),
                            Email = "alice.walker@learnconnect.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Walker",
                            PasswordHash = "$2a$11$UIFAwQK9vtD/em02ykdOI.319TsZdep/orrwvek/hfypBpHiDjztq",
                            Role = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 5, 683, DateTimeKind.Utc).AddTicks(1436),
                            Email = "robert.vance@learnconnect.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Vance",
                            PasswordHash = "$2a$11$FtfIrl6p5N7AMuYGO9b25OZhr24QwXqnG6rE93u.flv81XTxje63e",
                            Role = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 6, 96, DateTimeKind.Utc).AddTicks(4894),
                            Email = "john.doe@learnconnect.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$X/vESYSw1CIex8gKRJ2Hj.kJoqjO165WHO64mEs6c9bwSJb996LKO",
                            Role = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 6, 505, DateTimeKind.Utc).AddTicks(5278),
                            Email = "marie.curie@learnconnect.com",
                            FirstName = "Marie",
                            IsActive = true,
                            LastName = "Curie",
                            PasswordHash = "$2a$11$tHYe1L0bE6yE5sFJ1BtwW.mdFSjVfbQw2ZkcqpO1.3N4.hqMA9idS",
                            Role = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 6, 808, DateTimeKind.Utc).AddTicks(4807),
                            Email = "walter.white@learnconnect.com",
                            FirstName = "Walter",
                            IsActive = true,
                            LastName = "White",
                            PasswordHash = "$2a$11$hmM38RDEqFgnIMaZvqnkvutPUjwn2J/AMyjR71WojHMoXnK88NlHC",
                            Role = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 7, 88, DateTimeKind.Utc).AddTicks(7667),
                            Email = "heisenberg@learnconnect.com",
                            FirstName = "Werner",
                            IsActive = true,
                            LastName = "Heisenberg",
                            PasswordHash = "$2a$11$Abhrhsgp/KoMIXQV6.5QkOS1NFl1DFsf34cErUJ5Cin7n2FDLkr9e",
                            Role = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 7, 289, DateTimeKind.Utc).AddTicks(488),
                            Email = "jane.goodall@learnconnect.com",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Goodall",
                            PasswordHash = "$2a$11$aFaM7qf0N49ggUw8dWDVK.MMSEPW7ppANFWfVw27rbyxuFTlssbgC",
                            Role = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 7, 608, DateTimeKind.Utc).AddTicks(9638),
                            Email = "gregor.mendel@learnconnect.com",
                            FirstName = "Gregor",
                            IsActive = true,
                            LastName = "Mendel",
                            PasswordHash = "$2a$11$JSOvFRzNqK7RrAIMbAV.rObWGoHZ21n8hQ0w7nXa3eGyATl2E857u",
                            Role = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 7, 941, DateTimeKind.Utc).AddTicks(8894),
                            Email = "new.grad@learnconnect.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Dickinson",
                            PasswordHash = "$2a$11$xUB4VhuRChuW150Ri4rutOHRRMm/nE6dcR49jJG/j691mRtot1tdG",
                            Role = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 9, 19, DateTimeKind.Utc).AddTicks(2272),
                            Email = "shakespeare@learnconnect.com",
                            FirstName = "William",
                            IsActive = true,
                            LastName = "Shakespeare",
                            PasswordHash = "$2a$11$1Q1wAgCXg43QMQxkmdtCButZIWGg6vCa0JaotAT8JL0lEr./TO7c6",
                            Role = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 9, 518, DateTimeKind.Utc).AddTicks(859),
                            Email = "carlos.ruiz@learnconnect.com",
                            FirstName = "Carlos",
                            IsActive = true,
                            LastName = "Ruiz",
                            PasswordHash = "$2a$11$IgZOpwL7DQU77MWhQcEQQ.5ZwQmbfAtyxvKCbPSsiMCfLxNAwDVHi",
                            Role = 1
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 10, 91, DateTimeKind.Utc).AddTicks(6082),
                            Email = "isabela.madrigal@learnconnect.com",
                            FirstName = "Isabela",
                            IsActive = true,
                            LastName = "Madrigal",
                            PasswordHash = "$2a$11$YaqEOOBsEDIc4xYzg/MYeOz7zDP8EXWmA2vFmZGkpB64kot0K6Z2y",
                            Role = 1
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 10, 271, DateTimeKind.Utc).AddTicks(4622),
                            Email = "pierre.escargot@learnconnect.com",
                            FirstName = "Pierre",
                            IsActive = true,
                            LastName = "Escargot",
                            PasswordHash = "$2a$11$rUBpSRa8O9bndbJ6trc97OpNaP4ThoOVel.FUtCIbQvjizC8hm5u2",
                            Role = 1
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 10, 691, DateTimeKind.Utc).AddTicks(9795),
                            Email = "chef.gusteau@learnconnect.com",
                            FirstName = "Auguste",
                            IsActive = true,
                            LastName = "Gusteau",
                            PasswordHash = "$2a$11$t91VH8OsQJYzpJ4PGRiGQO26WXSehYBLwgN3lAs6f6u9LQ4JapPCS",
                            Role = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 11, 8, DateTimeKind.Utc).AddTicks(35),
                            Email = "script.kiddie@learnconnect.com",
                            FirstName = "Kevin",
                            IsActive = true,
                            LastName = "Mitnick",
                            PasswordHash = "$2a$11$xfDZJAUzWNVmddTMm3ZyZ.R8WNsnnXb56z52eIqeR0wLcGmk13UyC",
                            Role = 1
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 11, 302, DateTimeKind.Utc).AddTicks(6056),
                            Email = "dev.ops@learnconnect.com",
                            FirstName = "Linus",
                            IsActive = true,
                            LastName = "Torvalds",
                            PasswordHash = "$2a$11$C7AiS/jcxSr/GtcFjsbKw.UFVWr4c/UwERN.8AxDTHm3PvEMXQppe",
                            Role = 1
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 11, 673, DateTimeKind.Utc).AddTicks(9548),
                            Email = "ai.researcher@learnconnect.com",
                            FirstName = "Ada",
                            IsActive = true,
                            LastName = "Lovelace",
                            PasswordHash = "$2a$11$grOueZDfjYoZA3VXhU4WT.7KIpAjVWyvb/ff9M4YKc9IMMeXWgFNq",
                            Role = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 12, 61, DateTimeKind.Utc).AddTicks(3418),
                            Email = "time.traveler@learnconnect.com",
                            FirstName = "Marty",
                            IsActive = true,
                            LastName = "McFly",
                            PasswordHash = "$2a$11$7S8vqZsj70FBPjyPKdWj1.0uubkJ3hOaKi1OCelEnrjT4jfeXngim",
                            Role = 1
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 12, 377, DateTimeKind.Utc).AddTicks(9519),
                            Email = "museum.guide@learnconnect.com",
                            FirstName = "Indiana",
                            IsActive = true,
                            LastName = "Jones",
                            PasswordHash = "$2a$11$BiOcINEuBChcpol3l2DDoeLqjB7wjTTH40Vw4Qbt7F1LZmMAg1an2",
                            Role = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 12, 685, DateTimeKind.Utc).AddTicks(7086),
                            Email = "book.worm@learnconnect.com",
                            FirstName = "Hermione",
                            IsActive = true,
                            LastName = "Granger",
                            PasswordHash = "$2a$11$rIvLwv.Bax9w5T8VkXCOcunN9Mh5geIOvNs3pY0Dq22Z8SOkctVVO",
                            Role = 1
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 12, 997, DateTimeKind.Utc).AddTicks(8653),
                            Email = "published.author@learnconnect.com",
                            FirstName = "J.K.",
                            IsActive = true,
                            LastName = "Rowling",
                            PasswordHash = "$2a$11$Hc1SaDnVkIYVeRHgCh.QaOIiDaSMem2vssYGEE07TJypS7z7ZBdYy",
                            Role = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 13, 280, DateTimeKind.Utc).AddTicks(9618),
                            Email = "street.performer@learnconnect.com",
                            FirstName = "Ed",
                            IsActive = true,
                            LastName = "Sheeran",
                            PasswordHash = "$2a$11$qlWTsv9CDJflh8FgWsgTLekhrmvxfBuczpY0GrbwqKIUbnWh0SDNW",
                            Role = 1
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 3, 22, 21, 27, 13, 714, DateTimeKind.Utc).AddTicks(8029),
                            Email = "concert.pianist@learnconnect.com",
                            FirstName = "Ludwig",
                            IsActive = true,
                            LastName = "Beethoven",
                            PasswordHash = "$2a$11$X8g1/zpp8uVVrxmkDx0YnuyfxNXVw2PE8EAD2dXDVb5YCjlPuNpvK",
                            Role = 1
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.Lesson", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonNotebook", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Message", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LearnConnect.API.Models.ParentMeetingRequest", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Payment", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Reservation", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Reservations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Review", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Reviews")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Schedule", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("LearnConnect.API.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnConnect.API.Models.StudentBadge", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Badges")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("LearnConnect.API.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnConnect.API.Models.TeacherSubject", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("LearnConnect.API.Models.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
