// <auto-generated />
using System;
using LearnConnect.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LearnConnect.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LearnConnect.API.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("LessonPackageId")
                        .HasColumnType("integer");

                    b.Property<string>("MeetingLink")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonPackageId");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonNotebook", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonNotebooks");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonPackage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RemainingLessons")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("LessonPackages");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LearnConnect.API.Models.ParentMeetingRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<string>("Reason")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("ParentMeetingRequests");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Method")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<string>("TransactionId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("RequestedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Reviews");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeacherId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrentStreak")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastLessonDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<int?>("ParentUserId")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("StudentName")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CurrentStreak = 0,
                            ExperiencePoints = 0,
                            Level = 1,
                            Location = "New York, USA",
                            PhoneNumber = "+1234567890",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.StudentBadge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentBadges");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Subjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Science",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Science",
                            Name = "Physics"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Science",
                            Name = "Chemistry"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Science",
                            Name = "Biology"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Languages",
                            Name = "English"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Languages",
                            Name = "Spanish"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Languages",
                            Name = "French"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Technology",
                            Name = "Computer Science"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Technology",
                            Name = "Programming"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Humanities",
                            Name = "History"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Humanities",
                            Name = "Literature"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Arts",
                            Name = "Music"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Arts",
                            Name = "Piano"
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CertificateUrl")
                        .HasColumnType("text");

                    b.Property<string>("Education")
                        .HasColumnType("text");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Languages")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<DateTime?>("MemberSince")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("ResponseTime")
                        .HasColumnType("text");

                    b.Property<int>("TotalLessons")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("text");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YearsOfExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.7999999999999998,
                            Bio = "Experienced mathematics teacher with 10+ years of teaching experience. Specialized in calculus and algebra.",
                            Education = "PhD in Mathematics, MIT",
                            HourlyRate = 45.00m,
                            Languages = "English,Spanish",
                            Location = "Boston, USA",
                            MemberSince = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567891",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 250,
                            UserId = 3,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 4.9000000000000004,
                            Bio = "Computer Science expert specializing in Python, Java, and web development. Former software engineer at Google.",
                            Education = "MS in Computer Science, Stanford University",
                            HourlyRate = 60.00m,
                            Languages = "English,Mandarin",
                            Location = "San Francisco, USA",
                            MemberSince = new DateTime(2021, 3, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567892",
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 180,
                            UserId = 4,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 4.7000000000000002,
                            Bio = "Native English speaker with TEFL certification. Helping students improve their English communication skills.",
                            Education = "BA in English Literature, Oxford University",
                            HourlyRate = 35.00m,
                            Languages = "English,French",
                            Location = "London, UK",
                            MemberSince = new DateTime(2019, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567893",
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 320,
                            UserId = 5,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2019, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 4,
                            AverageRating = 4.9000000000000004,
                            Bio = "Physics enthusiast with a passion for making complex concepts simple. Specialized in mechanics and electromagnetism.",
                            Education = "PhD in Physics, Caltech",
                            HourlyRate = 50.00m,
                            Languages = "English,Spanish,Portuguese",
                            Location = "Chicago, USA",
                            MemberSince = new DateTime(2018, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567894",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 290,
                            UserId = 6,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2018, 9, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 5,
                            AverageRating = 5.0,
                            Bio = "Professional pianist and music teacher. Teaching piano, music theory, and composition for all levels.",
                            Education = "Master of Music, Juilliard School",
                            HourlyRate = 40.00m,
                            Languages = "English,German,Italian",
                            Location = "Vienna, Austria",
                            MemberSince = new DateTime(2017, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567895",
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 450,
                            UserId = 7,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2017, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 6,
                            AverageRating = 4.5999999999999996,
                            Bio = "Chemistry teacher with expertise in organic and inorganic chemistry. Making chemistry fun and understandable!",
                            Education = "PhD in Chemistry, University of Toronto",
                            HourlyRate = 42.00m,
                            Languages = "English,French",
                            Location = "Toronto, Canada",
                            MemberSince = new DateTime(2020, 5, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567896",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 210,
                            UserId = 8,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 5, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 9
                        },
                        new
                        {
                            Id = 7,
                            AverageRating = 4.7999999999999998,
                            Bio = "Native Spanish speaker offering conversational Spanish lessons. Learn Spanish the natural way!",
                            Education = "BA in Spanish Linguistics, Universidad Complutense",
                            HourlyRate = 30.00m,
                            Languages = "Spanish,English,Catalan",
                            Location = "Madrid, Spain",
                            MemberSince = new DateTime(2021, 8, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567897",
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 380,
                            UserId = 9,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 8,
                            AverageRating = 4.7000000000000002,
                            Bio = "History professor specializing in World War II and American history. Bringing history to life through engaging storytelling.",
                            Education = "PhD in History, Harvard University",
                            HourlyRate = 38.00m,
                            Languages = "English",
                            Location = "Washington DC, USA",
                            MemberSince = new DateTime(2016, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567898",
                            ResponseTime = "Within 5 hours",
                            TotalLessons = 340,
                            UserId = 10,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2016, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 9,
                            AverageRating = 4.9000000000000004,
                            Bio = "Biology teacher with a focus on molecular biology and genetics. PhD researcher turned educator.",
                            Education = "PhD in Molecular Biology, Cambridge University",
                            HourlyRate = 48.00m,
                            Languages = "English,French",
                            Location = "Cambridge, UK",
                            MemberSince = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567899",
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 195,
                            UserId = 11,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 7
                        },
                        new
                        {
                            Id = 10,
                            AverageRating = 4.7999999999999998,
                            Bio = "French language expert offering lessons from beginner to advanced. Certified DELF/DALF examiner.",
                            Education = "MA in French Literature, Sorbonne University",
                            HourlyRate = 36.00m,
                            Languages = "French,English,Spanish",
                            Location = "Paris, France",
                            MemberSince = new DateTime(2019, 4, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PhoneNumber = "+1234567800",
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 420,
                            UserId = 12,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2019, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 11
                        },
                        new
                        {
                            Id = 20,
                            AverageRating = 4.5,
                            Bio = "Math enthusiast helping students love numbers.",
                            Education = "BS Math",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 50,
                            UserId = 20,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 8, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 21,
                            AverageRating = 5.0,
                            Bio = "Advanced mathematics for serious students.",
                            Education = "PhD Math",
                            HourlyRate = 75.00m,
                            Languages = "English",
                            Location = "New York",
                            MemberSince = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 500,
                            UserId = 21,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 22,
                            AverageRating = 4.5999999999999996,
                            Bio = "Physics made simple and fun.",
                            Education = "BS Physics",
                            HourlyRate = 28.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 80,
                            UserId = 22,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 6, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 23,
                            AverageRating = 4.9000000000000004,
                            Bio = "Expert physics tutoring for university level.",
                            Education = "PhD Physics",
                            HourlyRate = 70.00m,
                            Languages = "English,French",
                            Location = "Paris",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 6 hours",
                            TotalLessons = 300,
                            UserId = 23,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 24,
                            AverageRating = 4.7000000000000002,
                            Bio = "High school chemistry support.",
                            Education = "BS Chemistry",
                            HourlyRate = 30.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 120,
                            UserId = 24,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 4
                        },
                        new
                        {
                            Id = 25,
                            AverageRating = 5.0,
                            Bio = "Advanced organic chemistry and lab prep.",
                            Education = "PhD Chemistry",
                            HourlyRate = 80.00m,
                            Languages = "English,German",
                            Location = "Berlin",
                            MemberSince = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 24 hours",
                            TotalLessons = 600,
                            UserId = 25,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 25
                        },
                        new
                        {
                            Id = 26,
                            AverageRating = 4.4000000000000004,
                            Bio = "Biology basics for everyone.",
                            Education = "BS Biology",
                            HourlyRate = 22.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 30,
                            UserId = 26,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 27,
                            AverageRating = 4.7999999999999998,
                            Bio = "Genetics and evolutionary biology expert.",
                            Education = "MS Biology",
                            HourlyRate = 45.00m,
                            Languages = "English,German",
                            Location = "Vienna",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 200,
                            UserId = 27,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 8
                        },
                        new
                        {
                            Id = 28,
                            AverageRating = 4.2999999999999998,
                            Bio = "English conversation and grammar.",
                            Education = "BA English",
                            HourlyRate = 20.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 40,
                            UserId = 28,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 1
                        },
                        new
                        {
                            Id = 29,
                            AverageRating = 4.9000000000000004,
                            Bio = "Literature analysis and creative writing.",
                            Education = "MFA Writing",
                            HourlyRate = 65.00m,
                            Languages = "English",
                            Location = "London",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 5 hours",
                            TotalLessons = 350,
                            UserId = 29,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 30,
                            AverageRating = 4.7000000000000002,
                            Bio = "Spanish for travel and business.",
                            Education = "BA Spanish",
                            HourlyRate = 40.00m,
                            Languages = "Spanish,English",
                            Location = "Barcelona",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 150,
                            UserId = 30,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 6
                        },
                        new
                        {
                            Id = 31,
                            AverageRating = 4.9000000000000004,
                            Bio = "Native Spanish speaker, advanced levels.",
                            Education = "MA Linguistics",
                            HourlyRate = 60.00m,
                            Languages = "Spanish,English",
                            Location = "Madrid",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 3 hours",
                            TotalLessons = 280,
                            UserId = 31,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 32,
                            AverageRating = 4.5,
                            Bio = "Learn French basics quickly.",
                            Education = "BA French",
                            HourlyRate = 25.00m,
                            Languages = "French,English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 60,
                            UserId = 32,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 33,
                            AverageRating = 5.0,
                            Bio = "Master French cuisine and language.",
                            Education = "Culinary Arts",
                            HourlyRate = 70.00m,
                            Languages = "French,English",
                            Location = "Paris",
                            MemberSince = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 8 hours",
                            TotalLessons = 400,
                            UserId = 33,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2021, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 34,
                            AverageRating = 4.5999999999999996,
                            Bio = "Intro to coding and cybersecurity.",
                            Education = "Self-taught",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 90,
                            UserId = 34,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 35,
                            AverageRating = 4.7999999999999998,
                            Bio = "DevOps, Linux, and System Admin.",
                            Education = "MS CS",
                            HourlyRate = 55.00m,
                            Languages = "English,Finnish",
                            Location = "Helsinki",
                            MemberSince = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 4 hours",
                            TotalLessons = 220,
                            UserId = 35,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 10
                        },
                        new
                        {
                            Id = 36,
                            AverageRating = 5.0,
                            Bio = "Artificial Intelligence and Machine Learning.",
                            Education = "PhD CS",
                            HourlyRate = 90.00m,
                            Languages = "English",
                            Location = "San Francisco",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 180,
                            UserId = 36,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 12
                        },
                        new
                        {
                            Id = 37,
                            AverageRating = 4.4000000000000004,
                            Bio = "History through the ages.",
                            Education = "BA History",
                            HourlyRate = 20.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2023, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 1 hour",
                            TotalLessons = 45,
                            UserId = 37,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 2
                        },
                        new
                        {
                            Id = 38,
                            AverageRating = 4.7999999999999998,
                            Bio = "Archaeology and ancient civilizations.",
                            Education = "PhD Archaeology",
                            HourlyRate = 40.00m,
                            Languages = "English",
                            Location = "Cairo",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 6 hours",
                            TotalLessons = 300,
                            UserId = 38,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 15
                        },
                        new
                        {
                            Id = 39,
                            AverageRating = 4.7000000000000002,
                            Bio = "Reading comprehension and book clubs.",
                            Education = "BA Lit",
                            HourlyRate = 22.00m,
                            Languages = "English",
                            Location = "Online",
                            MemberSince = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 100,
                            UserId = 39,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2024, 1, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 3
                        },
                        new
                        {
                            Id = 40,
                            AverageRating = 4.9000000000000004,
                            Bio = "Creative writing masterclass.",
                            Education = "BA Classics",
                            HourlyRate = 65.00m,
                            Languages = "English",
                            Location = "Edinburgh",
                            MemberSince = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 24 hours",
                            TotalLessons = 500,
                            UserId = 40,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2020, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 20
                        },
                        new
                        {
                            Id = 41,
                            AverageRating = 4.7999999999999998,
                            Bio = "Guitar and pop music basics.",
                            Education = "Self-taught",
                            HourlyRate = 25.00m,
                            Languages = "English",
                            Location = "London",
                            MemberSince = new DateTime(2022, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 2 hours",
                            TotalLessons = 150,
                            UserId = 41,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2022, 1, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 5
                        },
                        new
                        {
                            Id = 42,
                            AverageRating = 5.0,
                            Bio = "Classical piano and composition.",
                            Education = "Conservatory",
                            HourlyRate = 85.00m,
                            Languages = "German,English",
                            Location = "Vienna",
                            MemberSince = new DateTime(2018, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ResponseTime = "Within 12 hours",
                            TotalLessons = 800,
                            UserId = 42,
                            VerificationStatus = "Verified",
                            VerifiedAt = new DateTime(2018, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            YearsOfExperience = 30
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.TeacherSubject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherSubjects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            SubjectId = 1,
                            TeacherId = 1
                        },
                        new
                        {
                            Id = 2,
                            SubjectId = 8,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 3,
                            SubjectId = 9,
                            TeacherId = 2
                        },
                        new
                        {
                            Id = 4,
                            SubjectId = 5,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 5,
                            SubjectId = 11,
                            TeacherId = 3
                        },
                        new
                        {
                            Id = 6,
                            SubjectId = 2,
                            TeacherId = 4
                        },
                        new
                        {
                            Id = 7,
                            SubjectId = 12,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 8,
                            SubjectId = 13,
                            TeacherId = 5
                        },
                        new
                        {
                            Id = 9,
                            SubjectId = 3,
                            TeacherId = 6
                        },
                        new
                        {
                            Id = 10,
                            SubjectId = 6,
                            TeacherId = 7
                        },
                        new
                        {
                            Id = 11,
                            SubjectId = 10,
                            TeacherId = 8
                        },
                        new
                        {
                            Id = 12,
                            SubjectId = 4,
                            TeacherId = 9
                        },
                        new
                        {
                            Id = 13,
                            SubjectId = 7,
                            TeacherId = 10
                        },
                        new
                        {
                            Id = 14,
                            SubjectId = 11,
                            TeacherId = 10
                        },
                        new
                        {
                            Id = 20,
                            SubjectId = 1,
                            TeacherId = 20
                        },
                        new
                        {
                            Id = 21,
                            SubjectId = 1,
                            TeacherId = 21
                        },
                        new
                        {
                            Id = 22,
                            SubjectId = 2,
                            TeacherId = 22
                        },
                        new
                        {
                            Id = 23,
                            SubjectId = 2,
                            TeacherId = 23
                        },
                        new
                        {
                            Id = 24,
                            SubjectId = 3,
                            TeacherId = 24
                        },
                        new
                        {
                            Id = 25,
                            SubjectId = 3,
                            TeacherId = 25
                        },
                        new
                        {
                            Id = 26,
                            SubjectId = 4,
                            TeacherId = 26
                        },
                        new
                        {
                            Id = 27,
                            SubjectId = 4,
                            TeacherId = 27
                        },
                        new
                        {
                            Id = 28,
                            SubjectId = 5,
                            TeacherId = 28
                        },
                        new
                        {
                            Id = 29,
                            SubjectId = 5,
                            TeacherId = 29
                        },
                        new
                        {
                            Id = 30,
                            SubjectId = 6,
                            TeacherId = 30
                        },
                        new
                        {
                            Id = 31,
                            SubjectId = 6,
                            TeacherId = 31
                        },
                        new
                        {
                            Id = 32,
                            SubjectId = 7,
                            TeacherId = 32
                        },
                        new
                        {
                            Id = 33,
                            SubjectId = 7,
                            TeacherId = 33
                        },
                        new
                        {
                            Id = 34,
                            SubjectId = 8,
                            TeacherId = 34
                        },
                        new
                        {
                            Id = 35,
                            SubjectId = 9,
                            TeacherId = 34
                        },
                        new
                        {
                            Id = 36,
                            SubjectId = 8,
                            TeacherId = 35
                        },
                        new
                        {
                            Id = 37,
                            SubjectId = 9,
                            TeacherId = 35
                        },
                        new
                        {
                            Id = 38,
                            SubjectId = 8,
                            TeacherId = 36
                        },
                        new
                        {
                            Id = 39,
                            SubjectId = 9,
                            TeacherId = 36
                        },
                        new
                        {
                            Id = 40,
                            SubjectId = 10,
                            TeacherId = 37
                        },
                        new
                        {
                            Id = 41,
                            SubjectId = 10,
                            TeacherId = 38
                        },
                        new
                        {
                            Id = 42,
                            SubjectId = 11,
                            TeacherId = 39
                        },
                        new
                        {
                            Id = 43,
                            SubjectId = 11,
                            TeacherId = 40
                        },
                        new
                        {
                            Id = 44,
                            SubjectId = 12,
                            TeacherId = 41
                        },
                        new
                        {
                            Id = 45,
                            SubjectId = 13,
                            TeacherId = 41
                        },
                        new
                        {
                            Id = 46,
                            SubjectId = 12,
                            TeacherId = 42
                        },
                        new
                        {
                            Id = 47,
                            SubjectId = 13,
                            TeacherId = 42
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 1, 934, DateTimeKind.Utc).AddTicks(6115),
                            Email = "admin@learnconnect.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$NFxDUfE1eZFpUnRpj5Reb.6C8Af2zrzp8X6h67mYnIGPKLvrSGvQy",
                            Role = 2
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 2, 104, DateTimeKind.Utc).AddTicks(9400),
                            Email = "student@test.com",
                            FirstName = "Test",
                            IsActive = true,
                            LastName = "Student",
                            PasswordHash = "$2a$11$8UGdpXz/OVcSUa1QFBTXkudSn90D4IM.CofnXYnkPG70kV/RUGJdG",
                            Role = 0
                        },
                        new
                        {
                            Id = 50,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 2, 275, DateTimeKind.Utc).AddTicks(2695),
                            Email = "parent@test.com",
                            FirstName = "Test",
                            IsActive = true,
                            LastName = "Parent",
                            PasswordHash = "$2a$11$sdu92qHB371uXecuKU5U2uj3xXz21YNrq0eHcCJ7DVwtqtu/KbnQi",
                            Role = 3
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 2, 449, DateTimeKind.Utc).AddTicks(7914),
                            Email = "sarah.johnson@learnconnect.com",
                            FirstName = "Sarah",
                            IsActive = true,
                            LastName = "Johnson",
                            PasswordHash = "$2a$11$L8QByiYxWXfm7SZMyK48xONLWhbWumZlmAHEZvvqed0hNWLKg8WNi",
                            Role = 1
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 2, 607, DateTimeKind.Utc).AddTicks(2382),
                            Email = "michael.chen@learnconnect.com",
                            FirstName = "Michael",
                            IsActive = true,
                            LastName = "Chen",
                            PasswordHash = "$2a$11$uK7RHyiuwlJnulMeL.Fa7u3TBasppNhM7krUNkxQdrr6ffyV9hCm6",
                            Role = 1
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 2, 797, DateTimeKind.Utc).AddTicks(7683),
                            Email = "emma.davis@learnconnect.com",
                            FirstName = "Emma",
                            IsActive = true,
                            LastName = "Davis",
                            PasswordHash = "$2a$11$66MS6/Mg2AO.s4PTGDujGuvrYtc4luyxFfnW4kuSz0wz3xXrVnhQq",
                            Role = 1
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 2, 999, DateTimeKind.Utc).AddTicks(8090),
                            Email = "david.martinez@learnconnect.com",
                            FirstName = "David",
                            IsActive = true,
                            LastName = "Martinez",
                            PasswordHash = "$2a$11$MhnK.8FuEPxw9qduat3XnOFstpre/VO2H3YxBo0Vtz49llN/8O/mm",
                            Role = 1
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 3, 161, DateTimeKind.Utc).AddTicks(9785),
                            Email = "lisa.anderson@learnconnect.com",
                            FirstName = "Lisa",
                            IsActive = true,
                            LastName = "Anderson",
                            PasswordHash = "$2a$11$o3KmTIf3l3P9IGYauwHJHO6aIpJLMrl38MFPTgDK03FsrMvJeSc1.",
                            Role = 1
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 3, 320, DateTimeKind.Utc).AddTicks(1208),
                            Email = "james.wilson@learnconnect.com",
                            FirstName = "James",
                            IsActive = true,
                            LastName = "Wilson",
                            PasswordHash = "$2a$11$aV7kSjKno8Oz1IVwVy5uUOM6UPh2ddG4ajyVWvBUsW/y3CiKa1hwu",
                            Role = 1
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 3, 482, DateTimeKind.Utc).AddTicks(6334),
                            Email = "sophia.garcia@learnconnect.com",
                            FirstName = "Sophia",
                            IsActive = true,
                            LastName = "Garcia",
                            PasswordHash = "$2a$11$DP5Gf2Wv7ljkYuJHCPGuk.CX.FYu1RfqkOWtVD9y1T8h47z57EEC6",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 3, 674, DateTimeKind.Utc).AddTicks(2136),
                            Email = "robert.brown@learnconnect.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Brown",
                            PasswordHash = "$2a$11$hf2vG0X1XRoIjkzacyaBmuUimgR.8fmFj6teT3Vxwzwed7WrdYNei",
                            Role = 1
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 3, 861, DateTimeKind.Utc).AddTicks(2194),
                            Email = "olivia.taylor@learnconnect.com",
                            FirstName = "Olivia",
                            IsActive = true,
                            LastName = "Taylor",
                            PasswordHash = "$2a$11$2eb/GcG62tMrho.QEHnhru7GuHrpHMUk/LedNrv4sGRwjUSDQkeNK",
                            Role = 1
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 4, 40, DateTimeKind.Utc).AddTicks(6207),
                            Email = "daniel.moore@learnconnect.com",
                            FirstName = "Daniel",
                            IsActive = true,
                            LastName = "Moore",
                            PasswordHash = "$2a$11$Tu/tIJUs.i.ySLODxR0ejuZ8JsXZG6qiV8rmvQ0g8Adh9pMTU2nEW",
                            Role = 1
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 4, 217, DateTimeKind.Utc).AddTicks(2079),
                            Email = "alice.walker@learnconnect.com",
                            FirstName = "Alice",
                            IsActive = true,
                            LastName = "Walker",
                            PasswordHash = "$2a$11$RWaZeyH9GjJYlEquA8xj4elDjOnyuAgeN/Pgg71BaccTWbajZw2JC",
                            Role = 1
                        },
                        new
                        {
                            Id = 21,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 4, 377, DateTimeKind.Utc).AddTicks(142),
                            Email = "robert.vance@learnconnect.com",
                            FirstName = "Robert",
                            IsActive = true,
                            LastName = "Vance",
                            PasswordHash = "$2a$11$g5Ja1lciDEAvY4Vl8T8enO0yKzU81PgExktagT1KVu2d48vddTcEO",
                            Role = 1
                        },
                        new
                        {
                            Id = 22,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 4, 573, DateTimeKind.Utc).AddTicks(8164),
                            Email = "john.doe@learnconnect.com",
                            FirstName = "John",
                            IsActive = true,
                            LastName = "Doe",
                            PasswordHash = "$2a$11$bYF2xaZLQ.aJlQQaoXuxNe70SNd5sfRfZaejf3oFOVKF6mt8APvh2",
                            Role = 1
                        },
                        new
                        {
                            Id = 23,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 4, 771, DateTimeKind.Utc).AddTicks(4629),
                            Email = "marie.curie@learnconnect.com",
                            FirstName = "Marie",
                            IsActive = true,
                            LastName = "Curie",
                            PasswordHash = "$2a$11$pY8pOY6G93RVXeh5.fqpiu7fSLx.AxRh449zFzmEk6moyf.qf2Yk6",
                            Role = 1
                        },
                        new
                        {
                            Id = 24,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 4, 946, DateTimeKind.Utc).AddTicks(7661),
                            Email = "walter.white@learnconnect.com",
                            FirstName = "Walter",
                            IsActive = true,
                            LastName = "White",
                            PasswordHash = "$2a$11$/rL6QzfGNzv0Ysw7Q5qiF.CjNsOdLD5E0ECjWe5NBy5iXfI.SPWlW",
                            Role = 1
                        },
                        new
                        {
                            Id = 25,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 5, 154, DateTimeKind.Utc).AddTicks(2010),
                            Email = "heisenberg@learnconnect.com",
                            FirstName = "Werner",
                            IsActive = true,
                            LastName = "Heisenberg",
                            PasswordHash = "$2a$11$dq22.L6GqCRjAIz7HICpV.stymmSccWZZnN00Vqik.C3d7Gu1Fyj.",
                            Role = 1
                        },
                        new
                        {
                            Id = 26,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 5, 319, DateTimeKind.Utc).AddTicks(7413),
                            Email = "jane.goodall@learnconnect.com",
                            FirstName = "Jane",
                            IsActive = true,
                            LastName = "Goodall",
                            PasswordHash = "$2a$11$IU1RqVqtC.WT2kCdq6YxsuW.12iep1lBQKO2/WntEVqpoDuYTf7.e",
                            Role = 1
                        },
                        new
                        {
                            Id = 27,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 5, 513, DateTimeKind.Utc).AddTicks(4481),
                            Email = "gregor.mendel@learnconnect.com",
                            FirstName = "Gregor",
                            IsActive = true,
                            LastName = "Mendel",
                            PasswordHash = "$2a$11$jZrv14KTMyFb1Oyuhcff5.BYmRIKXZHRpe9fVJyWoD/mrdo1q2fQS",
                            Role = 1
                        },
                        new
                        {
                            Id = 28,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 5, 676, DateTimeKind.Utc).AddTicks(8907),
                            Email = "new.grad@learnconnect.com",
                            FirstName = "Emily",
                            IsActive = true,
                            LastName = "Dickinson",
                            PasswordHash = "$2a$11$vdMdIGj/GRUtJTgxXVvStehKcvfh6ZQFkh9fLFX82UO7aVwcN6T5W",
                            Role = 1
                        },
                        new
                        {
                            Id = 29,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 5, 868, DateTimeKind.Utc).AddTicks(1185),
                            Email = "shakespeare@learnconnect.com",
                            FirstName = "William",
                            IsActive = true,
                            LastName = "Shakespeare",
                            PasswordHash = "$2a$11$MGLVLDR5R90GfR6Ge8yDmOUxHRXZ9EtdfQCvPuec2LPcFKZsOTb22",
                            Role = 1
                        },
                        new
                        {
                            Id = 30,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 6, 70, DateTimeKind.Utc).AddTicks(5029),
                            Email = "carlos.ruiz@learnconnect.com",
                            FirstName = "Carlos",
                            IsActive = true,
                            LastName = "Ruiz",
                            PasswordHash = "$2a$11$ZuSLTelyMurLyhyDIoAZxuMhBsdIYK.LEFcFBdaYJfpR//A8i4GU.",
                            Role = 1
                        },
                        new
                        {
                            Id = 31,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 6, 253, DateTimeKind.Utc).AddTicks(3693),
                            Email = "isabela.madrigal@learnconnect.com",
                            FirstName = "Isabela",
                            IsActive = true,
                            LastName = "Madrigal",
                            PasswordHash = "$2a$11$UjRMw2B8eGRdzgVpVxNSwOr2T2tPdE.V3bfCU9kpWlt8/78vJZNfq",
                            Role = 1
                        },
                        new
                        {
                            Id = 32,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 6, 462, DateTimeKind.Utc).AddTicks(6117),
                            Email = "pierre.escargot@learnconnect.com",
                            FirstName = "Pierre",
                            IsActive = true,
                            LastName = "Escargot",
                            PasswordHash = "$2a$11$xZg.qYWLl5fwYb94osUepOtAqNTCO4kOZ6AgWSYA7uqcJdJcp2ovu",
                            Role = 1
                        },
                        new
                        {
                            Id = 33,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 6, 629, DateTimeKind.Utc).AddTicks(9706),
                            Email = "chef.gusteau@learnconnect.com",
                            FirstName = "Auguste",
                            IsActive = true,
                            LastName = "Gusteau",
                            PasswordHash = "$2a$11$1XeBIDOhwYDI77SL4Y6fZuypMTwqWnsH4MJKlN2CAchJ95Hzwc/Nq",
                            Role = 1
                        },
                        new
                        {
                            Id = 34,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 6, 844, DateTimeKind.Utc).AddTicks(6827),
                            Email = "script.kiddie@learnconnect.com",
                            FirstName = "Kevin",
                            IsActive = true,
                            LastName = "Mitnick",
                            PasswordHash = "$2a$11$BeXxxlxiXoVJYI3UzTHll.m/Z/hhT78rHn85jVUg3xjXFV/kP9Ceq",
                            Role = 1
                        },
                        new
                        {
                            Id = 35,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 7, 21, DateTimeKind.Utc).AddTicks(9565),
                            Email = "dev.ops@learnconnect.com",
                            FirstName = "Linus",
                            IsActive = true,
                            LastName = "Torvalds",
                            PasswordHash = "$2a$11$F97oTGGM0SWAmv41gI5bKusc0M4ck/.C/FuzwSGM8POUsoiTz1bIq",
                            Role = 1
                        },
                        new
                        {
                            Id = 36,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 7, 197, DateTimeKind.Utc).AddTicks(8362),
                            Email = "ai.researcher@learnconnect.com",
                            FirstName = "Ada",
                            IsActive = true,
                            LastName = "Lovelace",
                            PasswordHash = "$2a$11$g41WAc4vI2C0VuN5HkER6.ZWMRi58touQ3h6U6QOKHeCWkRGhAgBe",
                            Role = 1
                        },
                        new
                        {
                            Id = 37,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 7, 371, DateTimeKind.Utc).AddTicks(9527),
                            Email = "time.traveler@learnconnect.com",
                            FirstName = "Marty",
                            IsActive = true,
                            LastName = "McFly",
                            PasswordHash = "$2a$11$xnZSH4R4HsphBEfnSRy7GusLcuH6eEYoqcbc.e.rFwy.MQ1MdhNLa",
                            Role = 1
                        },
                        new
                        {
                            Id = 38,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 7, 536, DateTimeKind.Utc).AddTicks(3245),
                            Email = "museum.guide@learnconnect.com",
                            FirstName = "Indiana",
                            IsActive = true,
                            LastName = "Jones",
                            PasswordHash = "$2a$11$WrN3sai/yV0kUCMplfw9euBLLMZ0Iq2C2xVECQJdCDRO4hsmoQutW",
                            Role = 1
                        },
                        new
                        {
                            Id = 39,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 7, 701, DateTimeKind.Utc).AddTicks(5957),
                            Email = "book.worm@learnconnect.com",
                            FirstName = "Hermione",
                            IsActive = true,
                            LastName = "Granger",
                            PasswordHash = "$2a$11$wxq622IQ8qv3OzImy1rDLO.9dkeiRmAxa6TpF9VWjNvZLKEHnzjYm",
                            Role = 1
                        },
                        new
                        {
                            Id = 40,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 7, 907, DateTimeKind.Utc).AddTicks(1317),
                            Email = "published.author@learnconnect.com",
                            FirstName = "J.K.",
                            IsActive = true,
                            LastName = "Rowling",
                            PasswordHash = "$2a$11$Lfcpwm793tvO4v9EgbCsrOoZmd1rqnEX9/DM7gQxMi444UpeF14Pm",
                            Role = 1
                        },
                        new
                        {
                            Id = 41,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 8, 152, DateTimeKind.Utc).AddTicks(3643),
                            Email = "street.performer@learnconnect.com",
                            FirstName = "Ed",
                            IsActive = true,
                            LastName = "Sheeran",
                            PasswordHash = "$2a$11$E52icxQWgHx8qgrCONfdUOjXjU.9z5IBrVbiwcoww0BBY90odvUYa",
                            Role = 1
                        },
                        new
                        {
                            Id = 42,
                            CreatedAt = new DateTime(2026, 5, 4, 9, 41, 8, 345, DateTimeKind.Utc).AddTicks(3957),
                            Email = "concert.pianist@learnconnect.com",
                            FirstName = "Ludwig",
                            IsActive = true,
                            LastName = "Beethoven",
                            PasswordHash = "$2a$11$UWxLZ4qquj7MMs9JcKDIyerf.1c7BAOcZk3R/7qP3L1V0tXlR53vu",
                            Role = 1
                        });
                });

            modelBuilder.Entity("LearnConnect.API.Models.Lesson", b =>
                {
                    b.HasOne("LearnConnect.API.Models.LessonPackage", "LessonPackage")
                        .WithMany("Lessons")
                        .HasForeignKey("LessonPackageId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId");

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Lessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LessonPackage");

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonNotebook", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonPackage", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Message", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.User", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("LearnConnect.API.Models.ParentMeetingRequest", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Payment", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Reservation", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Reservations")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Review", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Lesson", "Lesson")
                        .WithMany()
                        .HasForeignKey("LessonId");

                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Reviews")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Reviews")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Schedule", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("Schedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "User")
                        .WithOne("Student")
                        .HasForeignKey("LearnConnect.API.Models.Student", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnConnect.API.Models.StudentBadge", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Student", "Student")
                        .WithMany("Badges")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.HasOne("LearnConnect.API.Models.User", "User")
                        .WithOne("Teacher")
                        .HasForeignKey("LearnConnect.API.Models.Teacher", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("LearnConnect.API.Models.TeacherSubject", b =>
                {
                    b.HasOne("LearnConnect.API.Models.Subject", "Subject")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LearnConnect.API.Models.Teacher", "Teacher")
                        .WithMany("TeacherSubjects")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("LearnConnect.API.Models.LessonPackage", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Student", b =>
                {
                    b.Navigation("Badges");

                    b.Navigation("Reservations");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Subject", b =>
                {
                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("LearnConnect.API.Models.Teacher", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("Reviews");

                    b.Navigation("Schedules");

                    b.Navigation("TeacherSubjects");
                });

            modelBuilder.Entity("LearnConnect.API.Models.User", b =>
                {
                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });
#pragma warning restore 612, 618
        }
    }
}
